"""Export preprocessed BSDS sessions to MATLAB, for cross-checking against the
reference implementation (``scsnl/Cai_Multiple_Demand_System_2023``, ``BSDS/``).

Writes the same ``data`` cell array ``BayesianSwitchingDynamicalSystems.m`` expects
(one ``D x N`` double matrix per session) plus the fit options, and a companion
``*_run.m`` script that calls the reference fitter with matching ``max_nstates``/
``max_ldim``/``opt`` so the two runs are directly comparable. Feed it the same
``sessions`` list (already detrended + z-scored via
:func:`fastfuncstuff.dynamics.preprocess.preprocess_sessions`) that you pass to
:func:`fastfuncstuff.dynamics.bsds.model.fit_bsds`.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch
from scipy.io import savemat


def write_matlab_bsds_input(
    sessions: list,
    mat_path: str,
    *,
    max_nstates: int,
    max_ldim: int | None = None,
    n_iter: int = 100,
    n_init_iter: int = 10,
    n_init_learning: int = 10,
    tol: float = 1e-3,
    equalize_lengths: bool = True,
) -> str:
    """Write ``sessions`` + fit options to ``mat_path``, and a ``*_run.m`` script.

    ``max_ldim=None`` mirrors the reference (and ``fit_bsds``) default of
    ``D - 1``. Returns the path to the generated ``.m`` script.

    ``equalize_lengths`` (default True): the reference ``initPoteriors.m`` does
    ``cell2mat`` on per-run k-means label vectors, which requires **all runs to
    have the same length** — unequal lengths crash it (``cat`` dimension
    mismatch). When runs differ, all are truncated to the shortest so the
    exported ``.mat`` runs in the reference code; a note is printed. (Our own
    ``fit_bsds`` handles unequal lengths natively, so this only affects the
    MATLAB export, not the Python fit.)
    """
    if len(sessions) == 0:
        raise ValueError("sessions is empty")
    arrays = [
        (s.detach().cpu().numpy() if isinstance(s, torch.Tensor) else np.asarray(s))
        for s in sessions
    ]
    lengths = [a.shape[1] for a in arrays]
    if equalize_lengths and len(set(lengths)) > 1:
        min_t = min(lengths)
        n_trunc = sum(t != min_t for t in lengths)
        print(
            f"  [matlab export] runs have unequal lengths {sorted(set(lengths))}; "
            f"truncating {n_trunc} run(s) to {min_t} TRs so the reference MATLAB "
            "(equal-length assumption in initPoteriors) can load the data."
        )
        arrays = [a[:, :min_t] for a in arrays]

    data = np.empty((1, len(arrays)), dtype=object)
    for i, a in enumerate(arrays):
        data[0, i] = np.asarray(a, dtype=np.float64)

    d = data[0, 0].shape[0]
    ldim = max_ldim if max_ldim is not None else d - 1

    mat_path = str(mat_path)
    savemat(
        mat_path,
        {
            "data": data,
            "max_nstates": float(max_nstates),
            "max_ldim": float(ldim),
            "opt_n_iter": float(n_iter),
            "opt_n_init_iter": float(n_init_iter),
            "opt_n_init_learning": float(n_init_learning),
            "opt_tol": float(tol),
        },
    )

    stem = Path(mat_path).with_suffix("")
    m_path = f"{stem}_run.m"
    script = f"""% Auto-generated by fastfuncstuff.dynamics.bsds.export_matlab.
% Cross-checks ffs_bsds against the reference MATLAB BSDS on the same data and
% fit options. Point BSDS_REPO at a checkout of
% https://github.com/scsnl/Cai_Multiple_Demand_System_2023 (the BSDS/ folder),
% then run this script in MATLAB or Octave.
BSDS_REPO = '/path/to/Cai_Multiple_Demand_System_2023/BSDS';
addpath(genpath(BSDS_REPO));

S = load('{Path(mat_path).name}');
data = S.data;
opt.n_iter = S.opt_n_iter;
opt.n_init_iter = S.opt_n_init_iter;
opt.n_init_learning = S.opt_n_init_learning;
opt.tol = S.opt_tol;
opt.noise = 0;
opt.p_ref = 0.01;

model = BayesianSwitchingDynamicalSystems(data, S.max_nstates, S.max_ldim, opt);

fprintf('group occupancy:\\n');
disp(model.fractional_occupancy_group_wise);
fprintf('remaining states (union across sessions):\\n');
disp(unique(cell2mat(model.id_of_remaining_states)));

save('{Path(stem).name}_model.mat', 'model', '-v7.3');
"""
    Path(m_path).write_text(script)
    return m_path
