"""
Comprehensive tests for hrf_selection.py with progressive coverage.

Test layers:
1. Small: Unit tests for core functions (load_nuisance_file, HRF evaluation)
2. Medium: Sub-workflow tests (HRF library fitting, batched evaluation)
3. Large/E2E: Full pipeline tests with ground truth verification

Uses realistic fMRI simulation to verify:
- HRF selection recovers known optimal HRFs
- Cross-validation prevents overfitting
- Per-voxel HRF selection improves model fit
"""

import numpy as np
import pytest
import torch

from fastfuncstuff.design.hrf_selection import (
    fit_glm_hrf_library_with_xval,
    load_nuisance_file,
)
from fastfuncstuff.utils import get_device

# ---------------------------------------------------------------------------
# Shared helper: build minimal inputs for fit_glm_hrf_library_with_xval
# ---------------------------------------------------------------------------

def _build_hrf_test_inputs(
    true_hrf_idx: int = 0,
    n_runs: int = 3,
    n_tp_run: int = 60,
    tr: float = 2.0,
    microtime_dt: float = 0.1,
    n_conditions: int = 2,
    n_voxels: int = 20,
    noise_level: float = 0.3,
    seed: int = 42,
):
    """
    Build minimal fMRI-like inputs for testing fit_glm_hrf_library_with_xval.

    Returns (data, onset_matrix, hrf_library, run_starts, n_tp_total, tr).
    data is (n_voxels, n_tp_total).  The first n_voxels//2 have clear signal
    generated by hrf_library[true_hrf_idx]; the rest are pure noise.
    """
    from fastfuncstuff.design.matrices import convolve_hrf_microtime
    from fastfuncstuff.design.builder import create_onset_matrix_microtime

    torch.manual_seed(seed)
    n_tp_total = n_runs * n_tp_run
    run_starts = [i * n_tp_run for i in range(n_runs)]

    # Place 3 events per condition per run, spread across run
    spacing_tr = n_tp_run // (n_conditions * 3 + 1)
    all_onsets: list[list[np.ndarray]] = []
    for cond in range(n_conditions):
        cond_onsets = []
        for _ in range(n_runs):
            base = cond * 3
            event_trs = [base * spacing_tr + k * spacing_tr for k in range(3)]
            cond_onsets.append(np.array([t * tr for t in event_trs], dtype=float))
        all_onsets.append(cond_onsets)

    stim_durations = [0.0] * n_conditions
    onset_matrix = create_onset_matrix_microtime(
        all_onsets, run_starts, tr, n_tp_total, microtime_dt,
        stim_durations, torch.device("cpu"))

    # A small HRF library: 3 distinct HRFs at microtime resolution.
    # HRF 0 (fast): narrow peak at 5s; HRF 1 (canonical): peak at 6s;
    # HRF 2 (slow): peak at 8s.
    n_hrf_bins = int(round(32.0 / microtime_dt))
    t_hrf = np.arange(n_hrf_bins) * microtime_dt
    hrfs = []
    for peak_time in [5.0, 6.0, 8.0]:
        h = np.exp(-0.5 * ((t_hrf - peak_time) / 1.5) ** 2) - 0.35 * np.exp(
            -0.5 * ((t_hrf - (peak_time + 4)) / 3.0) ** 2)
        h = h / np.abs(h).max()
        hrfs.append(h)
    hrf_library = torch.from_numpy(np.stack(hrfs).astype(np.float32))  # (3, n_hrf_bins)

    # Simulate data: first half of voxels have signal from true_hrf
    true_hrf = hrf_library[true_hrf_idx]
    design_out = convolve_hrf_microtime(onset_matrix, true_hrf, n_tp_total, tr=tr,
                                        microtime_dt=microtime_dt,
                                        device=torch.device("cpu"))
    assert isinstance(design_out, torch.Tensor), "Expected tensor from convolve_hrf_microtime"

    betas_high = torch.randn(n_voxels // 2, n_conditions) * 3.0
    signal = betas_high @ design_out.T  # (n_voxels//2, n_tp_total)
    noise_high = torch.randn(n_voxels // 2, n_tp_total) * noise_level
    noise_low = torch.randn(n_voxels - n_voxels // 2, n_tp_total) * 1.0

    data = torch.cat([signal + noise_high, noise_low], dim=0)  # (n_voxels, n_tp_total)

    return data, onset_matrix, hrf_library, run_starts, n_tp_total, tr


@pytest.fixture
def device():
    return get_device()


# ============================================================================
# Layer 1: Small Tests - Unit tests for core functions
# ============================================================================

class TestHRFSelectionCoreFunctions:
    """Test core HRF selection functions."""

    def test_load_nuisance_file_basic(self, tmp_path):
        """Test loading basic nuisance file."""
        # Create a simple nuisance file
        nuisance_file = tmp_path / "motion.1D"
        n_timepoints = 100
        n_cols = 6

        # Write some data
        data = np.random.randn(n_timepoints, n_cols)
        np.savetxt(nuisance_file, data, delimiter=" ")

        # Load it back
        loaded = load_nuisance_file(nuisance_file)

        assert loaded.shape == (n_timepoints, n_cols), \
            f"Expected shape ({n_timepoints}, {n_cols}), got {loaded.shape}"
        assert np.allclose(loaded, data), "Loaded data should match original"

    def test_load_nuisance_file_with_comments(self, tmp_path):
        """Test loading nuisance file with AFNI-style comments."""
        nuisance_file = tmp_path / "motion.1D"

        # Write file with comments
        with open(nuisance_file, 'w') as f:
            f.write("# This is a comment\n")
            f.write("# Another comment\n")
            f.write("1.0 2.0 3.0\n")
            f.write("4.0 5.0 6.0\n")
            f.write("# Final comment\n")

        loaded = load_nuisance_file(nuisance_file)

        assert loaded.shape == (2, 3)
        assert np.allclose(loaded, [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

    def test_load_nuisance_file_single_column(self, tmp_path):
        """Test that single-column files are reshaped correctly."""
        nuisance_file = tmp_path / "physio.1D"

        # Write single column
        with open(nuisance_file, 'w') as f:
            for i in range(10):
                f.write(f"{i}\n")

        loaded = load_nuisance_file(nuisance_file)

        # Should be reshaped to (n_timepoints, 1)
        assert loaded.shape == (10, 1), f"Expected shape (10, 1), got {loaded.shape}"

    def test_load_nuisance_file_not_found(self, tmp_path):
        """Test error when file doesn't exist."""
        nuisance_file = tmp_path / "nonexistent.1D"

        with pytest.raises(FileNotFoundError, match="Nuisance file not found"):
            load_nuisance_file(nuisance_file)

    def test_load_nuisance_file_empty(self, tmp_path):
        """Test error when file is empty."""
        nuisance_file = tmp_path / "empty.1D"

        # Create empty file
        nuisance_file.touch()

        with pytest.raises(ValueError, match="empty or contains only comments"):
            load_nuisance_file(nuisance_file)

    def test_load_nuisance_file_wrong_length(self, tmp_path):
        """Test validation with expected_rows."""
        nuisance_file = tmp_path / "motion.1D"

        # Write 10 rows
        data = np.random.randn(10, 3)
        np.savetxt(nuisance_file, data)

        # Expect 20 rows - should raise error
        with pytest.raises(ValueError, match="has 10 rows, expected 20"):
            load_nuisance_file(nuisance_file, expected_rows=20)


# ============================================================================
# Layer 2: Medium Tests - Sub-workflow tests
# ============================================================================

class TestHRFSelectionSubWorkflows:
    """Test HRF selection sub-workflows."""

    def test_hrf_library_fitting_output_shapes(self, device):
        """
        fit_glm_hrf_library_with_xval returns HRFSelectionResults with
        correctly-shaped tensors for a 3-run, 20-voxel, 3-HRF setup.
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = (
            _build_hrf_test_inputs(n_runs=3, n_voxels=20))
        n_voxels = data.shape[0]
        n_hrfs = hrf_library.shape[0]

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        # Check required fields
        assert results.hrf_index is not None
        assert results.hrf_index.shape == (n_voxels,)
        assert results.hrf_index.min() >= 0
        assert results.hrf_index.max() < n_hrfs

        assert results.xval_r2_best is not None
        assert results.xval_r2_best.shape == (n_voxels,)
        assert torch.all(torch.isfinite(results.xval_r2_best))

        assert results.xval_r2_all_hrfs is not None
        assert results.xval_r2_all_hrfs.shape == (n_voxels, n_hrfs)
        assert torch.all(torch.isfinite(results.xval_r2_all_hrfs))

        assert results.xval_r2_canonical is not None
        assert results.xval_r2_canonical.shape == (n_voxels,)

    def test_hrf_library_fitting_finishes_without_error(self, device):
        """
        fit_glm_hrf_library_with_xval runs end-to-end without raising
        an exception for the minimal input configuration.
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = (
            _build_hrf_test_inputs(n_runs=2, n_voxels=10))

        # Should not raise
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        assert results is not None

    def test_per_voxel_hrf_selection_distinguishes_groups(self, device):
        """
        When two groups of voxels have signal generated by different HRFs
        (HRF 0 vs HRF 2), the majority of each group selects its own HRF.

        Uses high SNR (noise_level=0.1) to make the distinction clear.
        """
        from fastfuncstuff.design.matrices import convolve_hrf_microtime
        from fastfuncstuff.design.builder import create_onset_matrix_microtime

        torch.manual_seed(7)
        n_runs, n_tp_run, tr, microtime_dt = 4, 80, 2.0, 0.1
        n_conditions, n_voxels_per_group = 2, 15

        n_tp_total = n_runs * n_tp_run
        run_starts = [i * n_tp_run for i in range(n_runs)]

        spacing_tr = 8
        all_onsets: list[list[np.ndarray]] = []
        for cond in range(n_conditions):
            cond_onsets = []
            for _ in range(n_runs):
                event_trs = [cond * spacing_tr + k * (2 * spacing_tr) for k in range(3)]
                cond_onsets.append(np.array([t * tr for t in event_trs], dtype=float))
            all_onsets.append(cond_onsets)

        stim_durations = [0.0] * n_conditions
        onset_matrix = create_onset_matrix_microtime(
            all_onsets, run_starts, tr, n_tp_total, microtime_dt,
            stim_durations, torch.device("cpu"))

        # Build 3-HRF library
        n_hrf_bins = int(round(32.0 / microtime_dt))
        t_hrf = np.arange(n_hrf_bins) * microtime_dt
        hrfs = []
        for peak_time in [5.0, 6.0, 8.0]:
            h = np.exp(-0.5 * ((t_hrf - peak_time) / 1.5) ** 2) - 0.35 * np.exp(
                -0.5 * ((t_hrf - (peak_time + 4)) / 3.0) ** 2)
            h = h / np.abs(h).max()
            hrfs.append(h)
        hrf_library = torch.from_numpy(np.stack(hrfs).astype(np.float32))

        # Group A: generated by HRF 0 (fast), Group B: by HRF 2 (slow)
        data_parts = []
        for hrf_idx in [0, 2]:
            d_out = convolve_hrf_microtime(
                onset_matrix, hrf_library[hrf_idx], n_tp_total, tr=tr,
                microtime_dt=microtime_dt, device=torch.device("cpu"))
            assert isinstance(d_out, torch.Tensor)
            betas = torch.ones(n_voxels_per_group, n_conditions) * 5.0
            signal = betas @ d_out.T
            noise = torch.randn(n_voxels_per_group, n_tp_total) * 0.1
            data_parts.append(signal + noise)

        data = torch.cat(data_parts, dim=0)  # (2*n_voxels_per_group, n_tp_total)

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        group_a_idx = results.hrf_index[:n_voxels_per_group].cpu().numpy()
        group_b_idx = results.hrf_index[n_voxels_per_group:].cpu().numpy()

        # Majority of group A should pick HRF 0, group B should pick HRF 2
        frac_a_correct = (group_a_idx == 0).mean()
        frac_b_correct = (group_b_idx == 2).mean()

        assert frac_a_correct >= 0.6, (
            f"Group A (HRF 0) correct fraction too low: {frac_a_correct:.2f}")
        assert frac_b_correct >= 0.6, (
            f"Group B (HRF 2) correct fraction too low: {frac_b_correct:.2f}")


class TestHRFSelectionResults:
    """Test HRFSelectionResults container"""

    def test_hrf_selection_results_initialization(self, device):
        """Test that HRFSelectionResults can be initialized"""
        from fastfuncstuff.design.hrf_selection import HRFSelectionResults

        n_voxels = 20
        n_hrfs = 3

        # Create results object
        results = HRFSelectionResults()

        # Should have all required attributes (default None)
        assert hasattr(results, "hrf_index")
        assert hasattr(results, "xval_r2_best")
        assert hasattr(results, "xval_r2_all_hrfs")
        assert hasattr(results, "xval_r2_canonical")
        assert hasattr(results, "hrf_library")
        assert hasattr(results, "hrf_metadata")

        # Can set attributes
        results.hrf_index = torch.zeros(n_voxels, dtype=torch.long, device=device)
        results.xval_r2_best = torch.randn(n_voxels, device=device)
        results.xval_r2_all_hrfs = torch.randn(n_voxels, n_hrfs, device=device)
        results.hrf_metadata = {"mode": "per_voxel", "tr": 2.0}

        assert results.hrf_index.shape == (n_voxels,)


# ============================================================================
# Layer 3: Large/E2E Tests - Full pipeline with ground truth
# ============================================================================

class TestHRFSelectionFullPipeline:
    """Test full HRF selection pipeline."""

    def test_hrf_selection_recovers_known_hrf(self, device):
        """
        When data is generated by HRF 2 (slow peak at 8s), the majority of
        high-SNR voxels should select HRF index 2 from a 3-HRF library.
        """
        true_hrf_idx = 2
        data, onset_matrix, hrf_library, run_starts, _, tr = (
            _build_hrf_test_inputs(
                true_hrf_idx=true_hrf_idx,
                n_runs=4,
                n_tp_run=80,
                n_voxels=40,
                noise_level=0.1,
                seed=77,
            )
        )
        n_high = data.shape[0] // 2  # first half has signal

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        high_snr_selected = results.hrf_index[:n_high].cpu().numpy()
        frac_correct = (high_snr_selected == true_hrf_idx).mean()
        assert frac_correct >= 0.6, (
            f"Expected ≥60% of high-SNR voxels to select HRF {true_hrf_idx}, "
            f"got {frac_correct:.1%}")

    def test_cv_prevents_overfitting(self, device):
        """
        Cross-validated R² should be ≤ in-sample R² for at least the majority
        of voxels (CV R² is a conservative estimate of generalization).

        We check xval_r2_best ≤ xval_r2_all_hrfs.max(dim=1) * 1.1, i.e.
        the selected CV R² is not higher than the best in-sample R² by a
        large margin (they should be similar or CV slightly lower).
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = (
            _build_hrf_test_inputs(n_runs=3, n_voxels=20, noise_level=0.3, seed=13)
        )

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        # xval_r2_best is the max CV R² across HRFs (per voxel)
        # xval_r2_all_hrfs has CV R² for each HRF — they should match
        if results.xval_r2_all_hrfs is not None and results.xval_r2_best is not None:
            r2_all = results.xval_r2_all_hrfs  # (n_voxels, n_hrfs)
            r2_best = results.xval_r2_best      # (n_voxels,)
            # Best CV R² is simply the max across HRFs — must match
            r2_all_max = r2_all.max(dim=1).values
            assert torch.allclose(r2_best, r2_all_max, atol=1e-4), (
                "xval_r2_best should equal the max over all HRFs in xval_r2_all_hrfs")

    def test_hrf_selection_vs_canonical(self, device):
        """
        When data is generated by a non-canonical HRF (HRF 0, peak at 5s),
        the per-voxel selected HRF should give higher CV R² than the canonical
        HRF (HRF 1, peak at 6s) for the majority of high-SNR voxels.
        """
        true_hrf_idx = 0  # fastest HRF in our library
        canonical_idx = 1  # middle HRF (canonical)

        data, onset_matrix, hrf_library, run_starts, _, tr = (
            _build_hrf_test_inputs(
                true_hrf_idx=true_hrf_idx,
                n_runs=4,
                n_tp_run=80,
                n_voxels=40,
                noise_level=0.1,
                seed=55,
            )
        )
        n_high = data.shape[0] // 2

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        if results.xval_r2_all_hrfs is not None:
            r2_all = results.xval_r2_all_hrfs  # (n_voxels, n_hrfs)
            r2_selected = results.xval_r2_best[:n_high]         # type: ignore[index]
            r2_canonical = r2_all[:n_high, canonical_idx]

            # Selected HRF should beat canonical for majority of high-SNR voxels
            frac_better = (r2_selected > r2_canonical).float().mean().item()
            assert frac_better >= 0.5, (
                f"Selected HRF should beat canonical for ≥50% of high-SNR voxels, "
                f"got {frac_better:.1%}")
