"""
Tests for the I/O surface of design/hrf_selection.py:

- load_nuisance_file — multi-format parsing of motion/physio files
- _write_afni_xmat — AFNI xmat.1D writer with labelled columns
- load_hrf_selection_for_arma — round-trip with torch.save

The per-voxel HRF pipeline is a CLAUDE.md principle. These utilities
are the joints between voxel-wise HRF selection and downstream
analyses; bugs here corrupt the design matrix or the reuse path.
"""

from __future__ import annotations

import numpy as np
import pytest
import torch

from fastfuncstuff.design.hrf_selection import (
    _write_afni_xmat,
    load_hrf_selection_for_arma,
    load_nuisance_file,
)

# ---------------------------------------------------------------------------
# load_nuisance_file
# ---------------------------------------------------------------------------


class TestLoadNuisanceFile:
    def test_afni_1d_whitespace(self, tmp_path):
        """AFNI .1D format: whitespace-separated, may have # comment headers."""
        p = tmp_path / "motion.1D"
        p.write_text(
            "# AFNI 1D file generated by 3dvolreg\n"
            "# 6 motion parameters\n"
            "0.0 0.0 0.0 0.0 0.0 0.0\n"
            "0.1 -0.2 0.05 0.001 -0.003 0.002\n"
            "0.15 -0.18 0.04 0.0005 -0.0028 0.0019\n"
        )
        data = load_nuisance_file(p)
        assert data.shape == (3, 6)
        assert data.dtype == np.float32
        np.testing.assert_allclose(data[0], np.zeros(6), atol=0)

    def test_csv_format(self, tmp_path):
        p = tmp_path / "physio.csv"
        p.write_text("0.0,1.0\n0.5,1.2\n0.7,1.4\n")
        data = load_nuisance_file(p)
        assert data.shape == (3, 2)
        np.testing.assert_allclose(data[1], [0.5, 1.2])

    def test_tab_separated(self, tmp_path):
        p = tmp_path / "physio.tsv"
        p.write_text("0.0\t1.0\n0.5\t1.2\n")
        data = load_nuisance_file(p)
        assert data.shape == (2, 2)

    def test_single_column_reshaped_to_2d(self, tmp_path):
        p = tmp_path / "single.1D"
        p.write_text("0.1\n0.2\n0.3\n")
        data = load_nuisance_file(p)
        assert data.shape == (3, 1)

    def test_expected_rows_validates(self, tmp_path):
        p = tmp_path / "motion.1D"
        p.write_text("0.1 0.2\n0.3 0.4\n")
        # Right count: OK
        data = load_nuisance_file(p, expected_rows=2)
        assert data.shape == (2, 2)
        # Wrong count: raises with the actual vs expected counts in the message
        with pytest.raises(ValueError, match="2 rows.*expected 100"):
            load_nuisance_file(p, expected_rows=100)

    def test_skips_blank_and_comment_lines(self, tmp_path):
        p = tmp_path / "motion.1D"
        p.write_text("# header\n\n0.1 0.2\n  \n# inline header\n0.3 0.4\n")
        data = load_nuisance_file(p)
        assert data.shape == (2, 2)

    def test_empty_file_raises(self, tmp_path):
        p = tmp_path / "empty.1D"
        p.write_text("# only a comment\n\n")
        with pytest.raises(ValueError, match="empty"):
            load_nuisance_file(p)

    def test_missing_file_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            load_nuisance_file(tmp_path / "missing.1D")

    def test_non_numeric_content_raises(self, tmp_path):
        p = tmp_path / "bad.1D"
        p.write_text("0.1 not_a_number\n0.3 0.4\n")
        with pytest.raises(ValueError, match="parsing"):
            load_nuisance_file(p)


# ---------------------------------------------------------------------------
# _write_afni_xmat
# ---------------------------------------------------------------------------


class TestWriteAfniXmat:
    def test_basic_header_attrs(self, tmp_path):
        T, n_stim, n_poly_total = 20, 2, 6
        X = np.random.default_rng(0).standard_normal((T, n_stim + n_poly_total)).astype(np.float32)
        out = tmp_path / "design.xmat.1D"
        _write_afni_xmat(
            X,
            str(out),
            n_stim_cols=n_stim,
            condition_labels=["A", "B"],
            run_starts=[0, 10],
            tr=2.0,
            polort=2,
        )
        text = out.read_text()
        assert "<matrix" in text
        assert f'ni_type = "{n_stim + n_poly_total}*double"' in text
        assert f'ni_dimen = "{T}"' in text
        assert 'RowTR = "2.0"' in text
        assert 'RunStart = "0,10"' in text
        assert 'Nstim = "2"' in text

    def test_polort_labels_per_run(self, tmp_path):
        """With polort=p and n_runs runs, labels are r01_poly0..r01_polyp,
        r02_poly0..r02_polyp, etc."""
        T, n_stim = 20, 2
        n_poly_total = 2 * 3  # 2 runs × (polort=2 → 3 polys)
        X = np.zeros((T, n_stim + n_poly_total))
        out = tmp_path / "design.xmat.1D"
        _write_afni_xmat(
            X,
            str(out),
            n_stim_cols=n_stim,
            condition_labels=["A", "B"],
            run_starts=[0, 10],
            tr=2.0,
            polort=2,
        )
        text = out.read_text()
        for r in (1, 2):
            for p in (0, 1, 2):
                assert f"r{r:02d}_poly{p}" in text

    def test_extra_nuisance_labels(self, tmp_path):
        T, n_stim = 20, 1
        n_poly = 2  # 1 run × (polort=1 → 2 polys)
        n_motion = 6
        X = np.zeros((T, n_stim + n_poly + n_motion))
        out = tmp_path / "design.xmat.1D"
        motion_labels = [f"motion_{i}" for i in range(6)]
        _write_afni_xmat(
            X,
            str(out),
            n_stim_cols=n_stim,
            condition_labels=["face"],
            run_starts=[0],
            tr=2.0,
            polort=1,
            extra_nuisance_labels=motion_labels,
        )
        text = out.read_text()
        for ml in motion_labels:
            assert ml in text

    def test_no_condition_labels_falls_back_to_stim_indices(self, tmp_path):
        T = 10
        X = np.zeros((T, 3))  # 2 stim + 1 nuisance
        out = tmp_path / "design.xmat.1D"
        _write_afni_xmat(
            X,
            str(out),
            n_stim_cols=2,
            condition_labels=None,
            run_starts=[0],
            tr=1.0,
            polort=0,
        )
        text = out.read_text()
        assert "stim00" in text
        assert "stim01" in text

    def test_data_rows_match_input_matrix(self, tmp_path):
        T = 5
        X = np.arange(T * 3, dtype=np.float32).reshape(T, 3)
        out = tmp_path / "design.xmat.1D"
        _write_afni_xmat(
            X,
            str(out),
            n_stim_cols=1,
            condition_labels=["A"],
            run_starts=[0],
            tr=2.0,
            polort=1,
        )
        # Read back data rows (everything not starting with '#')
        lines = out.read_text().splitlines()
        data_lines = [ln for ln in lines if ln and not ln.startswith("#")]
        assert len(data_lines) == T
        reloaded = np.array([[float(v) for v in ln.split()] for ln in data_lines])
        np.testing.assert_allclose(reloaded, X, atol=1e-5)


# ---------------------------------------------------------------------------
# load_hrf_selection_for_arma
# ---------------------------------------------------------------------------


class TestLoadHrfSelectionForArma:
    def test_round_trip_of_full_payload(self, tmp_path):
        """The function is a thin torch.load wrapper; the contract is that
        it returns the dict that was saved, including tensors and metadata."""
        payload = {
            "hrf_library": torch.randn(5, 30),
            "hrf_index": torch.tensor([0, 1, 2, 0, 1], dtype=torch.int64),
            "hrf_group_indices": {0: [0, 3], 1: [1, 4], 2: [2]},
            "metadata": {"tr": 2.0, "stim_durations": [3.0]},
        }
        f = tmp_path / "hrf_lib.pt"
        torch.save(payload, f)
        loaded = load_hrf_selection_for_arma(str(f))
        torch.testing.assert_close(loaded["hrf_library"], payload["hrf_library"])
        torch.testing.assert_close(loaded["hrf_index"], payload["hrf_index"])
        assert loaded["hrf_group_indices"] == payload["hrf_group_indices"]
        assert loaded["metadata"] == payload["metadata"]
