"""
Comprehensive tests for hrf_selection.py with progressive coverage.

Test layers:
1. Small: Unit tests for core functions (load_nuisance_file, HRF evaluation)
2. Medium: Sub-workflow tests (HRF library fitting, batched evaluation)
3. Large/E2E: Full pipeline tests with ground truth verification

Uses realistic fMRI simulation to verify:
- HRF selection recovers known optimal HRFs
- Cross-validation prevents overfitting
- Per-voxel HRF selection improves model fit
"""

import numpy as np
import pytest
import torch

from fastfuncstuff.design.hrf_selection import (
    HRFSelectionResults,
    _evaluate_hrfs_batched,
    _evaluate_hrfs_batched_loro,
    _project_design_with_q_factors,
    _write_afni_xmat,
    fit_glm_hrf_library_with_xval,
    load_nuisance_file,
    plot_design_matrix,
    plot_hrf_library,
)
from fastfuncstuff.utils import get_device

# ---------------------------------------------------------------------------
# Shared helper: build minimal inputs for fit_glm_hrf_library_with_xval
# ---------------------------------------------------------------------------


def _build_hrf_test_inputs(
    true_hrf_idx: int = 0,
    n_runs: int = 3,
    n_tp_run: int = 60,
    tr: float = 2.0,
    microtime_dt: float = 0.1,
    n_conditions: int = 2,
    n_voxels: int = 20,
    noise_level: float = 0.3,
    seed: int = 42,
):
    """
    Build minimal fMRI-like inputs for testing fit_glm_hrf_library_with_xval.

    Returns (data, onset_matrix, hrf_library, run_starts, n_tp_total, tr).
    data is (n_voxels, n_tp_total).  The first n_voxels//2 have clear signal
    generated by hrf_library[true_hrf_idx]; the rest are pure noise.
    """
    from fastfuncstuff.design.builder import create_onset_matrix_microtime
    from fastfuncstuff.design.matrices import convolve_hrf_microtime

    torch.manual_seed(seed)
    n_tp_total = n_runs * n_tp_run
    run_starts = [i * n_tp_run for i in range(n_runs)]

    # Place 3 events per condition per run, spread across run
    spacing_tr = n_tp_run // (n_conditions * 3 + 1)
    all_onsets: list[list[np.ndarray]] = []
    for cond in range(n_conditions):
        cond_onsets = []
        for _ in range(n_runs):
            base = cond * 3
            event_trs = [base * spacing_tr + k * spacing_tr for k in range(3)]
            cond_onsets.append(np.array([t * tr for t in event_trs], dtype=float))
        all_onsets.append(cond_onsets)

    stim_durations = [0.0] * n_conditions
    onset_matrix = create_onset_matrix_microtime(
        all_onsets, run_starts, tr, n_tp_total, microtime_dt, stim_durations, torch.device("cpu")
    )

    # A small HRF library: 3 distinct HRFs at microtime resolution.
    # HRF 0 (fast): narrow peak at 5s; HRF 1 (canonical): peak at 6s;
    # HRF 2 (slow): peak at 8s.
    n_hrf_bins = int(round(32.0 / microtime_dt))
    t_hrf = np.arange(n_hrf_bins) * microtime_dt
    hrfs = []
    for peak_time in [5.0, 6.0, 8.0]:
        h = np.exp(-0.5 * ((t_hrf - peak_time) / 1.5) ** 2) - 0.35 * np.exp(
            -0.5 * ((t_hrf - (peak_time + 4)) / 3.0) ** 2
        )
        h = h / np.abs(h).max()
        hrfs.append(h)
    hrf_library = torch.from_numpy(np.stack(hrfs).astype(np.float32))  # (3, n_hrf_bins)

    # Simulate data: first half of voxels have signal from true_hrf
    true_hrf = hrf_library[true_hrf_idx]
    design_out = convolve_hrf_microtime(
        onset_matrix,
        true_hrf,
        n_tp_total,
        tr=tr,
        microtime_dt=microtime_dt,
        device=torch.device("cpu"),
    )
    assert isinstance(design_out, torch.Tensor), "Expected tensor from convolve_hrf_microtime"

    betas_high = torch.randn(n_voxels // 2, n_conditions) * 3.0
    signal = betas_high @ design_out.T  # (n_voxels//2, n_tp_total)
    noise_high = torch.randn(n_voxels // 2, n_tp_total) * noise_level
    noise_low = torch.randn(n_voxels - n_voxels // 2, n_tp_total) * 1.0

    data = torch.cat([signal + noise_high, noise_low], dim=0)  # (n_voxels, n_tp_total)

    return data, onset_matrix, hrf_library, run_starts, n_tp_total, tr


def test_condition_level_library_uses_raw_events_not_binary_regions(monkeypatch):
    """Library selection must not reconstruct trials from merged duration boxes."""
    from fastfuncstuff.design.hrf_selection import fit_glm_hrf_library_with_xval
    from fastfuncstuff.design.matrices import build_event_design_microtime

    tr = 1.0
    dt = 0.5
    run_starts = [0, 20]
    event_onsets = [[np.array([2.0, 5.0]), np.array([2.0, 4.0])]]
    durations = [3.0]
    library = torch.tensor(
        [
            [0.0, 0.4, 1.0, 0.5, 0.1, 0.0],
            [0.0, 0.2, 0.7, 1.0, 0.6, 0.2],
        ]
    )
    truth = build_event_design_microtime(
        event_onsets,
        durations,
        library[1],
        [20, 20],
        tr=tr,
        microtime_dt=dt,
        device=torch.device("cpu"),
    )
    assert isinstance(truth, torch.Tensor)
    data = truth.T.repeat(4, 1)
    sampled_placeholder = torch.zeros(80, 1)

    def _legacy_path_is_a_bug(*args, **kwargs):
        raise AssertionError("raw events unexpectedly fell back to binary-region convolution")

    monkeypatch.setattr(
        "fastfuncstuff.design.hrf_selection.convolve_hrf_microtime", _legacy_path_is_a_bug
    )
    result = fit_glm_hrf_library_with_xval(
        data=data,
        onsets=sampled_placeholder,
        hrf_library=library,
        tr=tr,
        run_starts=run_starts,
        stim_durations=durations,
        microtime_dt=dt,
        polort=-1,
        select_mode="full",
        skip_final_fit=True,
        event_onsets=event_onsets,
        device=torch.device("cpu"),
        verbose=False,
    )
    assert result.hrf_index.shape == (4,)


@pytest.fixture
def device():
    return get_device()


# ============================================================================
# Layer 1: Small Tests - Unit tests for core functions
# ============================================================================


class TestHRFSelectionCoreFunctions:
    """Test core HRF selection functions."""

    def test_load_nuisance_file_basic(self, tmp_path):
        """Test loading basic nuisance file."""
        nuisance_file = tmp_path / "motion.1D"
        n_timepoints = 100
        n_cols = 6
        data = np.random.randn(n_timepoints, n_cols)
        np.savetxt(nuisance_file, data, delimiter=" ")
        loaded = load_nuisance_file(nuisance_file)
        assert loaded.shape == (n_timepoints, n_cols)
        assert np.allclose(loaded, data, atol=1e-5)

    def test_load_nuisance_file_with_comments(self, tmp_path):
        """Test loading nuisance file with AFNI-style comments."""
        nuisance_file = tmp_path / "motion.1D"
        with open(nuisance_file, "w") as f:
            f.write("# This is a comment\n")
            f.write("# Another comment\n")
            f.write("1.0 2.0 3.0\n")
            f.write("4.0 5.0 6.0\n")
            f.write("# Final comment\n")
        loaded = load_nuisance_file(nuisance_file)
        assert loaded.shape == (2, 3)
        assert np.allclose(loaded, [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

    def test_load_nuisance_file_single_column(self, tmp_path):
        """Test that single-column files are reshaped correctly."""
        nuisance_file = tmp_path / "physio.1D"
        with open(nuisance_file, "w") as f:
            for i in range(10):
                f.write(f"{i}\n")
        loaded = load_nuisance_file(nuisance_file)
        assert loaded.shape == (10, 1)

    def test_load_nuisance_file_not_found(self, tmp_path):
        """Test error when file doesn't exist."""
        with pytest.raises(FileNotFoundError, match="Nuisance file not found"):
            load_nuisance_file(tmp_path / "nonexistent.1D")

    def test_load_nuisance_file_empty(self, tmp_path):
        """Test error when file is empty."""
        nuisance_file = tmp_path / "empty.1D"
        nuisance_file.touch()
        with pytest.raises(ValueError, match="empty or contains only comments"):
            load_nuisance_file(nuisance_file)

    def test_load_nuisance_file_wrong_length(self, tmp_path):
        """Test validation with expected_rows."""
        nuisance_file = tmp_path / "motion.1D"
        np.savetxt(nuisance_file, np.random.randn(10, 3))
        with pytest.raises(ValueError, match="has 10 rows, expected 20"):
            load_nuisance_file(nuisance_file, expected_rows=20)

    def test_load_nuisance_file_csv(self, tmp_path):
        """Test loading CSV-delimited nuisance file (covers comma delimiter path)."""
        nuisance_file = tmp_path / "motion.csv"
        with open(nuisance_file, "w") as f:
            f.write("1.0,2.0,3.0\n")
            f.write("4.0,5.0,6.0\n")
        loaded = load_nuisance_file(nuisance_file)
        assert loaded.shape == (2, 3)
        assert np.allclose(loaded, [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

    def test_load_nuisance_file_tab_delimited(self, tmp_path):
        """Test loading tab-delimited nuisance file (covers tab delimiter path)."""
        nuisance_file = tmp_path / "motion.tsv"
        with open(nuisance_file, "w") as f:
            f.write("1.0\t2.0\t3.0\n")
            f.write("4.0\t5.0\t6.0\n")
        loaded = load_nuisance_file(nuisance_file)
        assert loaded.shape == (2, 3)
        assert np.allclose(loaded, [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

    def test_load_nuisance_file_parse_error(self, tmp_path):
        """Test error on unparseable file content."""
        nuisance_file = tmp_path / "bad.1D"
        with open(nuisance_file, "w") as f:
            f.write("abc def ghi\n")
        with pytest.raises(ValueError, match="Error parsing nuisance file"):
            load_nuisance_file(nuisance_file)


# ============================================================================
# Tests for _project_design_with_q_factors
# ============================================================================


class TestProjectDesignWithQFactors:
    """Test the QR-based nuisance projection for design matrices."""

    def test_identity_projection_when_no_nuisance(self):
        """When Q factors are None, design should pass through unchanged."""
        n_tp, n_cols = 60, 3
        design = torch.randn(n_tp, n_cols)
        q_factors = [None, None]
        run_starts = [0, 30]
        result = _project_design_with_q_factors(
            design, q_factors, run_starts, n_tp, 2, torch.device("cpu")
        )
        assert torch.allclose(result, design, atol=1e-6)

    def test_projection_removes_nuisance_component(self):
        """Projection should remove the component of design in Q's column space."""
        n_tp = 40
        # Build a simple Q factor (orthonormal columns)
        Q_raw = torch.randn(n_tp, 2)
        Q, _ = torch.linalg.qr(Q_raw)
        # Build a design that is partly in Q's column space
        design = Q @ torch.randn(2, 3) + torch.randn(n_tp, 3) * 0.1
        q_factors = [Q]
        run_starts = [0]
        result = _project_design_with_q_factors(
            design, q_factors, run_starts, n_tp, 1, torch.device("cpu")
        )
        # Projected design should be orthogonal to Q
        overlap = Q.T @ result
        assert overlap.abs().max() < 1e-4

    def test_multi_run_projection(self):
        """Each run should be projected independently."""
        n_tp_run = 30
        n_tp = 2 * n_tp_run
        Q1_raw = torch.randn(n_tp_run, 2)
        Q1, _ = torch.linalg.qr(Q1_raw)
        Q2_raw = torch.randn(n_tp_run, 2)
        Q2, _ = torch.linalg.qr(Q2_raw)
        design = torch.randn(n_tp, 3)
        result = _project_design_with_q_factors(
            design, [Q1, Q2], [0, n_tp_run], n_tp, 2, torch.device("cpu")
        )
        # Check each run's block is orthogonal to its Q factor
        overlap1 = Q1.T @ result[:n_tp_run]
        overlap2 = Q2.T @ result[n_tp_run:]
        assert overlap1.abs().max() < 1e-4
        assert overlap2.abs().max() < 1e-4


# ============================================================================
# Tests for _evaluate_hrfs_batched
# ============================================================================


class TestEvaluateHRFsBatched:
    """Test batched HRF evaluation via cross-validation."""

    def _make_simple_cv_data(self, n_runs=3, n_tp_run=40, n_voxels=10, n_designs=2):
        """Build simple projected data/designs for batched evaluation."""
        torch.manual_seed(99)
        n_tp = n_runs * n_tp_run
        run_starts = [i * n_tp_run for i in range(n_runs)]

        # Data: voxels x timepoints
        data = torch.randn(n_voxels, n_tp)

        # Two designs with different quality fits
        n_cols = 3
        designs = []
        for d in range(n_designs):
            X = torch.randn(n_tp, n_cols) * (1.0 + d * 0.5)
            designs.append(X)

        return data, designs, run_starts

    def test_loro_returns_correct_shape(self):
        """LORO evaluation returns (n_voxels, n_designs) R2."""
        data, designs, run_starts = self._make_simple_cv_data(n_runs=3)
        # LORO splits
        cv_splits = [([j for j in range(3) if j != i], [i]) for i in range(3)]
        r2 = _evaluate_hrfs_batched(
            data, designs, run_starts, cv_splits, torch.device("cpu"), verbose=False
        )
        assert r2.shape == (10, 2)
        assert torch.all(torch.isfinite(r2))

    def test_split_half_returns_correct_shape(self):
        """Split-half evaluation returns (n_voxels, n_designs) R2."""
        data, designs, run_starts = self._make_simple_cv_data(n_runs=4, n_tp_run=30)
        # Split-half: each test has 2 runs, so each TP in test twice across folds
        cv_splits = [
            ([0, 1], [2, 3]),
            ([2, 3], [0, 1]),
            ([0, 2], [1, 3]),
            ([1, 3], [0, 2]),
        ]
        r2 = _evaluate_hrfs_batched(
            data, designs, run_starts, cv_splits, torch.device("cpu"), verbose=False
        )
        assert r2.shape == (10, 2)
        assert torch.all(torch.isfinite(r2))

    def test_good_design_beats_noise_design(self):
        """A design correlated with data should have higher R2 than random noise."""
        torch.manual_seed(42)
        n_runs, n_tp_run, n_voxels = 3, 50, 20
        n_tp = n_runs * n_tp_run
        run_starts = [i * n_tp_run for i in range(n_runs)]

        # Good design: data is linear combo of design columns + noise
        X_good = torch.randn(n_tp, 3)
        betas = torch.randn(n_voxels, 3) * 2.0
        data = betas @ X_good.T + torch.randn(n_voxels, n_tp) * 0.3

        X_bad = torch.randn(n_tp, 3)  # uncorrelated noise design

        cv_splits = [([j for j in range(3) if j != i], [i]) for i in range(3)]
        r2 = _evaluate_hrfs_batched(
            data, [X_good, X_bad], run_starts, cv_splits, torch.device("cpu"), verbose=False
        )
        # Good design should have higher R2 on average
        assert r2[:, 0].mean() > r2[:, 1].mean()

    def test_loro_alias_matches(self):
        """_evaluate_hrfs_batched_loro should produce same result as _evaluate_hrfs_batched."""
        data, designs, run_starts = self._make_simple_cv_data(n_runs=3)
        cv_splits = [([j for j in range(3) if j != i], [i]) for i in range(3)]
        r2_main = _evaluate_hrfs_batched(
            data, designs, run_starts, cv_splits, torch.device("cpu"), verbose=False
        )
        r2_alias = _evaluate_hrfs_batched_loro(
            data, designs, run_starts, cv_splits, torch.device("cpu"), verbose=False
        )
        assert torch.allclose(r2_main, r2_alias)

    def test_explicit_chunk_size(self):
        """Setting chunk_size should still produce valid results."""
        data, designs, run_starts = self._make_simple_cv_data(n_runs=3, n_voxels=20)
        cv_splits = [([j for j in range(3) if j != i], [i]) for i in range(3)]
        r2 = _evaluate_hrfs_batched(
            data, designs, run_starts, cv_splits, torch.device("cpu"), chunk_size=5, verbose=False
        )
        assert r2.shape == (20, 2)
        assert torch.all(torch.isfinite(r2))

    def test_split_half_with_unequal_train_test(self):
        """Split-half where n_train < n_test triggers warning path."""
        import warnings

        data, designs, run_starts = self._make_simple_cv_data(n_runs=5, n_tp_run=20)
        # 2 train, 3 test -- n_train < n_test
        cv_splits = [
            ([0, 1], [2, 3, 4]),
            ([2, 3], [0, 1, 4]),
        ]
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            r2 = _evaluate_hrfs_batched(
                data, designs, run_starts, cv_splits, torch.device("cpu"), verbose=False
            )
        assert r2.shape == (10, 2)
        # Should have produced a warning about n_train < n_test
        assert any("training runs" in str(warning.message) for warning in w)


# ============================================================================
# Tests for _write_afni_xmat
# ============================================================================


class TestWriteAfniXmat:
    """Test AFNI xmat.1D file writing."""

    def test_basic_write(self, tmp_path):
        """Write a simple design matrix and verify format."""
        design = np.array([[1.0, 0.0, 0.5], [0.0, 1.0, 0.3], [0.5, 0.5, 0.1]])
        out_file = str(tmp_path / "test.xmat.1D")
        _write_afni_xmat(
            design,
            out_file,
            n_stim_cols=2,
            condition_labels=["face", "house"],
            run_starts=[0],
            tr=2.0,
            polort=1,
        )
        with open(out_file) as f:
            content = f.read()
        assert "face" in content
        assert "house" in content
        assert "ni_dimen" in content
        assert 'RowTR = "2.0"' in content
        # Verify data rows
        lines = [l for l in content.strip().split("\n") if not l.startswith("#")]
        assert len(lines) == 3

    def test_write_with_polort_labels(self, tmp_path):
        """Polort labels should follow r01_poly0 pattern."""
        n_tp, n_stim, n_nuis = 60, 2, 4
        design = np.random.randn(n_tp, n_stim + n_nuis)
        out_file = str(tmp_path / "test.xmat.1D")
        _write_afni_xmat(
            design,
            out_file,
            n_stim_cols=n_stim,
            condition_labels=None,
            run_starts=[0, 30],
            tr=2.0,
            polort=1,
        )
        with open(out_file) as f:
            content = f.read()
        assert "r01_poly0" in content
        assert "r02_poly1" in content
        assert "stim00" in content  # auto-generated label

    def test_write_with_extra_nuisance_labels(self, tmp_path):
        """Extra nuisance labels should appear in output."""
        n_tp = 30
        design = np.random.randn(n_tp, 5)  # 2 stim + 2 poly + 1 extra
        out_file = str(tmp_path / "test.xmat.1D")
        _write_afni_xmat(
            design,
            out_file,
            n_stim_cols=2,
            condition_labels=["cond_A", "cond_B"],
            run_starts=[0],
            tr=1.5,
            polort=1,
            extra_nuisance_labels=["motion_roll"],
        )
        with open(out_file) as f:
            content = f.read()
        assert "motion_roll" in content
        assert "cond_A" in content

    def test_write_no_stim_cols(self, tmp_path):
        """Edge case: 0 stim cols should still write valid header."""
        design = np.random.randn(20, 3)
        out_file = str(tmp_path / "test.xmat.1D")
        _write_afni_xmat(
            design, out_file, n_stim_cols=0, condition_labels=None, run_starts=[0], tr=2.0
        )
        with open(out_file) as f:
            content = f.read()
        assert 'Nstim = "0"' in content
        # Should NOT have StimBots/StimTops when n_stim_cols=0
        assert "StimBots" not in content

    def test_write_multiple_runs(self, tmp_path):
        """RunStart header should list all run starts."""
        design = np.random.randn(90, 4)
        out_file = str(tmp_path / "test.xmat.1D")
        _write_afni_xmat(
            design, out_file, n_stim_cols=2, condition_labels=None, run_starts=[0, 30, 60], tr=2.0
        )
        with open(out_file) as f:
            content = f.read()
        assert "0,30,60" in content


# ============================================================================
# Tests for plot functions (just verify they don't crash)
# ============================================================================


class TestPlotFunctions:
    """Test plotting functions produce output without errors."""

    def test_plot_design_matrix_to_file(self, tmp_path):
        """plot_design_matrix should save a PNG file."""
        design = torch.randn(100, 5)
        out_file = str(tmp_path / "design.png")
        plot_design_matrix(
            design,
            output_file=out_file,
            tr=2.0,
            column_labels=["a", "b", "c", "d", "e"],
            run_starts=[0, 50],
        )
        assert (tmp_path / "design.png").exists()

    def test_plot_design_matrix_numpy_input(self, tmp_path):
        """plot_design_matrix should accept numpy arrays."""
        design = np.random.randn(80, 3)
        out_file = str(tmp_path / "design_np.png")
        plot_design_matrix(design, output_file=out_file, tr=1.0)
        assert (tmp_path / "design_np.png").exists()

    def test_plot_design_matrix_many_columns(self, tmp_path):
        """plot_design_matrix with >20 columns should still work."""
        design = torch.randn(60, 25)
        out_file = str(tmp_path / "design_big.png")
        plot_design_matrix(design, output_file=out_file)
        assert (tmp_path / "design_big.png").exists()

    def test_plot_hrf_library_to_file(self, tmp_path):
        """plot_hrf_library should save a PNG file."""
        hrf_lib = torch.randn(5, 32)
        out_file = str(tmp_path / "hrfs.png")
        plot_hrf_library(hrf_lib, output_file=out_file, tr=0.1, highlight_idx=2)
        assert (tmp_path / "hrfs.png").exists()

    def test_plot_hrf_library_numpy_input(self, tmp_path):
        """plot_hrf_library should accept numpy arrays."""
        hrf_lib = np.random.randn(3, 50)
        out_file = str(tmp_path / "hrfs_np.png")
        plot_hrf_library(hrf_lib, output_file=out_file)
        assert (tmp_path / "hrfs_np.png").exists()

    def test_plot_hrf_library_single_hrf(self, tmp_path):
        """plot_hrf_library with a single HRF should not crash."""
        hrf_lib = torch.randn(1, 32)
        out_file = str(tmp_path / "hrf_single.png")
        plot_hrf_library(hrf_lib, output_file=out_file)
        assert (tmp_path / "hrf_single.png").exists()

    def test_plot_hrf_library_many_hrfs(self, tmp_path):
        """plot_hrf_library with >10 HRFs should skip legend."""
        hrf_lib = torch.randn(15, 32)
        out_file = str(tmp_path / "hrfs_many.png")
        plot_hrf_library(hrf_lib, output_file=out_file)
        assert (tmp_path / "hrfs_many.png").exists()


# ============================================================================
# Tests for HRFSelectionResults
# ============================================================================


class TestHRFSelectionResults:
    """Test HRFSelectionResults container"""

    def test_hrf_selection_results_initialization(self, device):
        """Test that HRFSelectionResults can be initialized"""
        n_voxels = 20
        n_hrfs = 3
        results = HRFSelectionResults()

        assert hasattr(results, "hrf_index")
        assert hasattr(results, "xval_r2_best")
        assert hasattr(results, "xval_r2_all_hrfs")
        assert hasattr(results, "xval_r2_canonical")
        assert hasattr(results, "hrf_library")
        assert hasattr(results, "hrf_metadata")

        results.hrf_index = torch.zeros(n_voxels, dtype=torch.long, device=device)
        results.xval_r2_best = torch.randn(n_voxels, device=device)
        results.xval_r2_all_hrfs = torch.randn(n_voxels, n_hrfs, device=device)
        results.hrf_metadata = {"mode": "per_voxel", "tr": 2.0}
        assert results.hrf_index.shape == (n_voxels,)

    def test_all_optional_fields_default_none(self):
        """All optional fields should be None by default."""
        r = HRFSelectionResults()
        assert r.hrf_index is None
        assert r.xval_r2_best is None
        assert r.xval_r2_std is None
        assert r.final_results is None
        assert r.canonical_results is None
        assert r.canonical_full_r2 is None
        assert r.hrfopt_full_r2 is None
        assert r.canonical_xval_r2 is None
        assert r.hrfopt_xval_r2 is None
        assert r.design_matrix is None
        assert r.canonical_design_matrix is None

    def test_dict_fields_default_empty(self):
        """Dict/list fields should default to empty."""
        r = HRFSelectionResults()
        assert r.hrf_metadata == {}
        assert r.hrf_group_indices == {}


# ============================================================================
# Layer 2: Medium Tests - Sub-workflow tests
# ============================================================================


class TestHRFSelectionSubWorkflows:
    """Test HRF selection sub-workflows."""

    def test_hrf_library_fitting_output_shapes(self, device):
        """
        fit_glm_hrf_library_with_xval returns HRFSelectionResults with
        correctly-shaped tensors for a 3-run, 20-voxel, 3-HRF setup.
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=20
        )
        n_voxels = data.shape[0]
        n_hrfs = hrf_library.shape[0]

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        assert results.hrf_index is not None
        assert results.hrf_index.shape == (n_voxels,)
        assert results.hrf_index.min() >= 0
        assert results.hrf_index.max() < n_hrfs

        assert results.xval_r2_best is not None
        assert results.xval_r2_best.shape == (n_voxels,)
        assert torch.all(torch.isfinite(results.xval_r2_best))

        assert results.xval_r2_all_hrfs is not None
        assert results.xval_r2_all_hrfs.shape == (n_voxels, n_hrfs)
        assert torch.all(torch.isfinite(results.xval_r2_all_hrfs))

        assert results.xval_r2_canonical is not None
        assert results.xval_r2_canonical.shape == (n_voxels,)

    def test_hrf_library_fitting_finishes_without_error(self, device):
        """
        fit_glm_hrf_library_with_xval runs end-to-end without raising
        an exception for the minimal input configuration.
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=2, n_voxels=10
        )

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        assert results is not None

    def test_per_voxel_hrf_selection_distinguishes_groups(self, device):
        """
        When two groups of voxels have signal generated by different HRFs
        (HRF 0 vs HRF 2), the majority of each group selects its own HRF.
        """
        from fastfuncstuff.design.builder import create_onset_matrix_microtime
        from fastfuncstuff.design.matrices import convolve_hrf_microtime

        torch.manual_seed(7)
        n_runs, n_tp_run, tr, microtime_dt = 4, 80, 2.0, 0.1
        n_conditions, n_voxels_per_group = 2, 15

        n_tp_total = n_runs * n_tp_run
        run_starts = [i * n_tp_run for i in range(n_runs)]

        spacing_tr = 8
        all_onsets: list[list[np.ndarray]] = []
        for cond in range(n_conditions):
            cond_onsets = []
            for _ in range(n_runs):
                event_trs = [cond * spacing_tr + k * (2 * spacing_tr) for k in range(3)]
                cond_onsets.append(np.array([t * tr for t in event_trs], dtype=float))
            all_onsets.append(cond_onsets)

        stim_durations = [0.0] * n_conditions
        onset_matrix = create_onset_matrix_microtime(
            all_onsets,
            run_starts,
            tr,
            n_tp_total,
            microtime_dt,
            stim_durations,
            torch.device("cpu"),
        )

        n_hrf_bins = int(round(32.0 / microtime_dt))
        t_hrf = np.arange(n_hrf_bins) * microtime_dt
        hrfs = []
        for peak_time in [5.0, 6.0, 8.0]:
            h = np.exp(-0.5 * ((t_hrf - peak_time) / 1.5) ** 2) - 0.35 * np.exp(
                -0.5 * ((t_hrf - (peak_time + 4)) / 3.0) ** 2
            )
            h = h / np.abs(h).max()
            hrfs.append(h)
        hrf_library = torch.from_numpy(np.stack(hrfs).astype(np.float32))

        data_parts = []
        for hrf_idx in [0, 2]:
            d_out = convolve_hrf_microtime(
                onset_matrix,
                hrf_library[hrf_idx],
                n_tp_total,
                tr=tr,
                microtime_dt=microtime_dt,
                device=torch.device("cpu"),
            )
            assert isinstance(d_out, torch.Tensor)
            betas = torch.ones(n_voxels_per_group, n_conditions) * 5.0
            signal = betas @ d_out.T
            noise = torch.randn(n_voxels_per_group, n_tp_total) * 0.1
            data_parts.append(signal + noise)

        data = torch.cat(data_parts, dim=0)

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        group_a_idx = results.hrf_index[:n_voxels_per_group].cpu().numpy()
        group_b_idx = results.hrf_index[n_voxels_per_group:].cpu().numpy()

        frac_a_correct = (group_a_idx == 0).mean()
        frac_b_correct = (group_b_idx == 2).mean()

        assert frac_a_correct >= 0.6, (
            f"Group A (HRF 0) correct fraction too low: {frac_a_correct:.2f}"
        )
        assert frac_b_correct >= 0.6, (
            f"Group B (HRF 2) correct fraction too low: {frac_b_correct:.2f}"
        )

    def test_extra_regressors_ndarray(self, device):
        """fit_glm_hrf_library_with_xval accepts extra_regressors as ndarray."""
        data, onset_matrix, hrf_library, run_starts, n_tp, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        extra = np.random.randn(n_tp, 2).astype(np.float32)
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
            extra_regressors=extra,
        )
        assert results is not None
        assert results.hrf_metadata["n_extra_nuisance"] == 2

    def test_extra_regressors_tensor(self, device):
        """fit_glm_hrf_library_with_xval accepts extra_regressors as tensor."""
        data, onset_matrix, hrf_library, run_starts, n_tp, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        extra = torch.randn(n_tp, 3)
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
            extra_regressors=extra,
        )
        assert results is not None
        assert results.hrf_metadata["n_extra_nuisance"] == 3

    def test_extra_regressors_1d(self, device):
        """1D extra_regressors should be reshaped to (n_tp, 1)."""
        data, onset_matrix, hrf_library, run_starts, n_tp, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        extra = np.random.randn(n_tp).astype(np.float32)
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
            extra_regressors=extra,
        )
        assert results.hrf_metadata["n_extra_nuisance"] == 1

    def test_canonical_mode_glmsingle(self, device):
        """canonical_mode='glmsingle' should use GLMsingle HRF."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
            canonical_mode="glmsingle",
        )
        assert results is not None

    def test_canonical_mode_invalid_raises(self, device):
        """Invalid canonical_mode should raise ValueError."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        with pytest.raises(ValueError, match="Unknown canonical_mode"):
            fit_glm_hrf_library_with_xval(
                data=data,
                onsets=onset_matrix,
                hrf_library=hrf_library,
                tr=tr,
                run_starts=run_starts,
                polort=1,
                verbose=False,
                device=device,
                canonical_mode="invalid_mode",
            )

    def test_data_timepoints_mismatch_raises(self, device):
        """Mismatched data/onset timepoints should raise ValueError."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        # Truncate data to create mismatch
        bad_data = data[:, : data.shape[1] - 5]
        with pytest.raises(ValueError, match="Data has .* timepoints but design implies"):
            fit_glm_hrf_library_with_xval(
                data=bad_data,
                onsets=onset_matrix,
                hrf_library=hrf_library,
                tr=tr,
                run_starts=run_starts,
                polort=1,
                verbose=False,
                device=device,
            )

    def test_metadata_fields(self, device):
        """Verify key metadata fields are populated."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        m = results.hrf_metadata
        assert m["tr"] == tr
        assert m["n_hrfs"] == 3
        assert m["n_runs"] == 3
        assert m["polort"] == 1
        assert "hrf_usage_counts" in m
        assert len(m["hrf_usage_counts"]) == 3

    def test_final_results_populated(self, device):
        """final_results and canonical_results should have betas/r2."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        assert results.final_results is not None
        assert results.final_results.betas is not None
        assert results.final_results.r2 is not None
        assert results.canonical_results is not None
        assert results.canonical_results.betas is not None

    def test_design_matrix_stored(self, device):
        """Design matrix and canonical design matrix should be stored."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        assert results.design_matrix is not None
        assert results.canonical_design_matrix is not None

    def test_hrf_group_indices_populated(self, device):
        """hrf_group_indices should map used HRFs to voxel indices."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=20
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )
        assert len(results.hrf_group_indices) > 0
        total_voxels = sum(len(v) for v in results.hrf_group_indices.values())
        assert total_voxels == 20

    def test_auto_polort(self, device):
        """polort=None should auto-compute polort from AFNI formula."""
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=10
        )
        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=None,
            verbose=False,
            device=device,
        )
        assert results.hrf_metadata["polort"] >= 1


# ============================================================================
# Layer 3: Large/E2E Tests - Full pipeline with ground truth
# ============================================================================


class TestHRFSelectionFullPipeline:
    """Test full HRF selection pipeline."""

    def test_hrf_selection_recovers_known_hrf(self, device):
        """
        When data is generated by HRF 2 (slow peak at 8s), the majority of
        high-SNR voxels should select HRF index 2 from a 3-HRF library.
        """
        true_hrf_idx = 2
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            true_hrf_idx=true_hrf_idx,
            n_runs=4,
            n_tp_run=80,
            n_voxels=40,
            noise_level=0.1,
            seed=77,
        )
        n_high = data.shape[0] // 2

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        high_snr_selected = results.hrf_index[:n_high].cpu().numpy()
        frac_correct = (high_snr_selected == true_hrf_idx).mean()
        assert frac_correct >= 0.6, (
            f"Expected >=60% of high-SNR voxels to select HRF {true_hrf_idx}, "
            f"got {frac_correct:.1%}"
        )

    def test_cv_prevents_overfitting(self, device):
        """
        Cross-validated R2 should be consistent: xval_r2_best should
        equal the max over xval_r2_all_hrfs.
        """
        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            n_runs=3, n_voxels=20, noise_level=0.3, seed=13
        )

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        if results.xval_r2_all_hrfs is not None and results.xval_r2_best is not None:
            r2_all = results.xval_r2_all_hrfs
            r2_best = results.xval_r2_best
            r2_all_max = r2_all.max(dim=1).values
            assert torch.allclose(r2_best, r2_all_max, atol=1e-4)

    def test_hrf_selection_vs_canonical(self, device):
        """
        When data is generated by a non-canonical HRF, per-voxel selected HRF
        should give higher CV R2 than canonical for majority of high-SNR voxels.
        """
        true_hrf_idx = 0
        canonical_idx = 1

        data, onset_matrix, hrf_library, run_starts, _, tr = _build_hrf_test_inputs(
            true_hrf_idx=true_hrf_idx,
            n_runs=4,
            n_tp_run=80,
            n_voxels=40,
            noise_level=0.1,
            seed=55,
        )
        n_high = data.shape[0] // 2

        results = fit_glm_hrf_library_with_xval(
            data=data,
            onsets=onset_matrix,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            verbose=False,
            device=device,
        )

        if results.xval_r2_all_hrfs is not None:
            r2_all = results.xval_r2_all_hrfs
            r2_selected = results.xval_r2_best[:n_high]
            r2_canonical = r2_all[:n_high, canonical_idx]

            frac_better = (r2_selected > r2_canonical).float().mean().item()
            assert frac_better >= 0.5, (
                f"Selected HRF should beat canonical for >=50% of high-SNR voxels, "
                f"got {frac_better:.1%}"
            )


class TestZeroVarianceVoxelHandling:
    """Background voxels are dropped before fitting and padded back afterwards.

    ffs_hrfopt always passes ``final_fit_data`` (it is the unblurred copy under
    -cv_blur, and the same tensor otherwise). That argument was not being subset
    with the rest, so any unmasked run — where background voxels exist — refit at
    full length against an active-length ``hrf_index`` and then crashed padding
    the results back out.
    """

    @pytest.mark.parametrize("separate_final_data", [False, True])
    def test_padding_survives_final_fit_data(self, separate_final_data):
        data, onsets, hrf_library, run_starts, n_tp, tr = _build_hrf_test_inputs(n_voxels=20)
        data[5:10] = 0.0  # background: no signal at all

        final_fit_data = data.clone() if separate_final_data else data

        results = fit_glm_hrf_library_with_xval(
            data=data,
            final_fit_data=final_fit_data,
            onsets=onsets,
            hrf_library=hrf_library,
            tr=tr,
            run_starts=run_starts,
            polort=1,
            device=torch.device("cpu"),
            verbose=False,
        )

        assert results.hrf_index.shape[0] == 20
        assert results.final_results is not None
        assert results.final_results.betas.shape[0] == 20
        # Dropped voxels come back as zeros, not as some other voxel's betas.
        assert torch.all(results.final_results.betas[5:10] == 0)
        assert torch.all(results.xval_r2_best[5:10] == 0)
        assert results.hrf_metadata["n_zero_voxels"] == 5
        assert results.hrf_metadata["n_active_voxels"] == 15

    def test_mismatched_final_fit_data_is_rejected(self):
        """A final_fit_data over a different voxel set would silently misassign HRFs."""
        data, onsets, hrf_library, run_starts, n_tp, tr = _build_hrf_test_inputs(n_voxels=20)
        data[5:10] = 0.0

        with pytest.raises(ValueError, match="same voxel set"):
            fit_glm_hrf_library_with_xval(
                data=data,
                final_fit_data=data[:15].clone(),
                onsets=onsets,
                hrf_library=hrf_library,
                tr=tr,
                run_starts=run_starts,
                polort=1,
                device=torch.device("cpu"),
                verbose=False,
            )
