#!/usr/bin/env python3

"""
ffs_blipflip - fast blip-up/blip-down susceptibility distortion correction.

A GPU (CPU-capable) implementation of the blip-up/blip-down method of Andersson,
Skare & Ashburner (2003): estimate one off-resonance field from two EPI images
acquired with opposing phase-encode polarity ("blip up" / "blip down"), and write a
single 4-D undistortion warp that ``ffs_nwarp`` composes with motion/coreg/atlas
transforms into one final resample.

Unlike FSL's ``topup``, there is no acquisition-parameter text file and no need to
concatenate the inputs beforehand: pass the two images (or an N-image list) with
their phase-encode direction and readout time on the command line. If an input is a
4-D timeseries it is collapsed (median by default) to one volume first. Motion
estimation is deferred; the only motion modelled is an optional single global
translation along the PE axis (``-pe_shift``), the tiny scanner-induced shift
possible between back-to-back scans.

    ffs_blipflip -blip_up AP.nii.gz -blip_down PA.nii.gz \\
                 -pe_dir j -readout 0.045 -prefix sub_dc

    # -> sub_dc_warp.nii.gz     (distorted[blip_up] -> undistorted "middle" space)
    #    sub_dc_invwarp.nii.gz  (undistorted "middle" -> distorted geometry; the inverse)
    #    sub_dc_field.nii.gz    (off-resonance field, Hz; needs -readout)
    #    sub_dc_unwarped.nii.gz + sub_dc_mean.nii.gz  (corrected inputs + mean)
    #    sub_dc_jac.nii.gz      (Jacobian modulation map)
    #
    # -readout is optional (the warp is insensitive to a common factor); omit it and the
    # Hz field map is simply not written. Precision tiers: default 9-level standard, or
    # -workhard (12 levels), or -superhard (14 levels, knots to 2 mm).

    # apply to the matching timeseries in one resample:
    ffs_nwarp -source epi.nii.gz -master epi.nii.gz \\
              -nwarp sub_dc_warp.nii.gz -prefix epi_dc.nii.gz

METHOD / CREDIT
  The groupwise blip-up/down field model -- one B-spline field, per-scan PE
  displacement plus Jacobian intensity modulation, bending-energy regularisation, and
  a coarse-to-fine schedule over knot spacing / smoothing / penalty weight -- is
  published in Andersson, Skare & Ashburner (2003), NeuroImage 20:870-888; see also
  Smith et al. (2004), NeuroImage 23:S208-219. The best-known implementation is FSL's
  ``topup``, by Jesper Andersson, FMRIB Analysis Group, University of Oxford.

  This tool is written from those papers. FSL source is not a reference for it, and
  the solver and schedule are our own: Gauss-Newton with a matrix-free CG normal-
  equation solve, a 1-D gather resample along PE, an explicit anti-fold barrier, and
  a schedule generated by ``processing.topup.make_ladder`` from a stated rule. See
  ../fmri_wiki/notes/FSL clean-room policy.md.
"""

from __future__ import annotations

import argparse
import re
import shlex
import sys
from datetime import datetime

import numpy as np
import torch

from fastfuncstuff.cli_help import FfsArgumentParser, FfsHelpFormatter, suggest

# What -pe_dir accepts. Offered rather than enforced (choices=) because the
# parser is deliberately lenient about how a direction is written.
PE_DIRECTION_WORDS = ("i", "j", "k", "i-", "j-", "k-", "x", "y", "z", "x-", "y-", "z-")
from fastfuncstuff.cli_utils import (
    add_batch_args,
    add_device_arg,
    add_warp_movie_args,
    build_warp_movie_recorder,
    collect_batch_jobs,
    parse_prefix,
    render_warp_movie,
    resolve_movie_path,
    run_batch_jobs,
    setup_device,
)
from fastfuncstuff.utils import REGISTRATION_TF32


def _float_list(s: str) -> list[float]:
    return [float(x) for x in s.replace(",", " ").split()]


def _int_list(s: str) -> list[int]:
    return [int(x) for x in s.replace(",", " ").split()]


def create_parser() -> argparse.ArgumentParser:
    parser = FfsArgumentParser(
        prog="ffs_blipflip",
        description="Blip-up/blip-down susceptibility distortion correction "
        "(blip-up/blip-down field model, Andersson et al. 2003).",
        formatter_class=FfsHelpFormatter,
        epilog=_schedule_epilog() + "\n\n" + __doc__.split("METHOD / CREDIT")[1].strip(),
    )

    inp = parser.add_argument_group("Inputs (pick the pair form OR -imain)")
    inp.add_argument("-blip_up", metavar="FILE", help="Blip-up EPI (3-D, or 4-D to collapse).")
    inp.add_argument("-blip_down", metavar="FILE", help="Blip-down EPI (opposite PE polarity).")
    inp.add_argument(
        "-imain",
        nargs="+",
        metavar="FILE",
        help="General N-image form: two or more EPIs. Needs matching -pe_dir/-readout "
        "lists (one entry each, or one shared value).",
    )
    suggest(
        inp.add_argument(
            "-pe_dir",
            "-pe-dir",
            nargs="+",
            metavar="DIR",
            help="Phase-encode direction of the blip_up (or of each -imain image): one of "
            "i/j/k (or x/y/z) with optional trailing '-'. The blip_down is the opposite.",
        ),
        PE_DIRECTION_WORDS,
    )
    inp.add_argument(
        "-readout",
        "-total_readout_time",
        nargs="+",
        type=float,
        default=None,
        metavar="SEC",
        help="Total readout time (s), one shared value or one per image. Optional: it only "
        "scales the Hz<->voxel conversion, and the warp is insensitive to a common factor. "
        "If omitted the warp is still correct, but the Hz field map cannot be written and is "
        "forced off.",
    )
    inp.add_argument(
        "-collapse",
        choices=("median", "mean"),
        default="median",
        help="How to collapse a 4-D input to one volume.",
    )

    out = parser.add_argument_group("Outputs")
    out.add_argument("-prefix", help="Output prefix (stem[.nii.gz]) [required unless -batch].")
    out.add_argument(
        "-warp_for",
        choices=("up", "down"),
        default="up",
        help="Which acquisition geometry the undistortion warp corrects.",
    )
    out.add_argument(
        "-no_invwarp",
        action="store_true",
        help="Do not write the inverse warp (undistorted 'middle' -> distorted geometry).",
    )
    out.add_argument("-no_fmap", action="store_true", help="Do not write the Hz field map.")
    out.add_argument(
        "-no_unwarped", action="store_true", help="Do not write corrected inputs + mean."
    )
    out.add_argument("-no_jac", action="store_true", help="Do not write the Jacobian map.")
    out.add_argument(
        "-no_mask_field",
        action="store_true",
        help="Do not taper the field to zero outside the object. By default the field "
        "(and warp) is rolled off in air so ffs_nwarp does not replicate tissue into an "
        "auto-pad margin; disable to keep the raw extrapolated field everywhere.",
    )

    sched = parser.add_argument_group("Schedule")
    sched.add_argument(
        "-config",
        choices=("standard", "quick", "workhard", "superhard"),
        default="standard",
        help="Preset schedule: 'quick' (3 levels), 'standard' (9 levels, default), "
        "'workhard' (12 levels — coarser start, longer descent, 1000x lower lambda and twice "
        "the iterations, for large fields), "
        "'superhard' (14 levels, as workhard but knots down to 2 mm, extra low-lambda "
        "refinement). Higher tiers are slower. Each tier's per-level lists are printed "
        "under SCHEDULE PRESETS at the end of -help, ready to copy.",
    )
    sched.add_argument(
        "-workhard",
        action="store_const",
        const="workhard",
        dest="config",
        help="Shortcut for -config workhard.",
    )
    sched.add_argument(
        "-superhard",
        action="store_const",
        const="superhard",
        dest="config",
        help="Shortcut for -config superhard (most precise, slowest).",
    )
    _per_level = (
        " One value per level (comma-separated), or a single value for every level. "
        "Default: the -config tier's list, shown under SCHEDULE PRESETS at the end of -help."
    )
    sched.add_argument(
        "-warpres", type=_float_list, metavar="MM,...", help="Knot spacing (mm)." + _per_level
    )
    sched.add_argument(
        "-fwhm", type=_float_list, metavar="MM,...", help="Data smoothing FWHM (mm)." + _per_level
    )
    sched.add_argument(
        "-lambda",
        dest="lam",
        type=_float_list,
        metavar="W,...",
        help="Bending-energy weight, relative to the data cost (see -no_ssqlambda)." + _per_level,
    )
    sched.add_argument(
        "-miter",
        type=_int_list,
        metavar="N,...",
        help="Max Gauss-Newton iterations; a level can end sooner (see -min_update)." + _per_level,
    )
    sched.add_argument(
        "-subsamp",
        type=_int_list,
        metavar="K,...",
        help="Integer subsampling factor (1 = full resolution)." + _per_level,
    )
    sched.add_argument(
        "-min_update",
        type=float,
        default=0.0,
        metavar="VOX",
        help="End a level once a Gauss-Newton step moves the displacement less than this many "
        "voxels (worst voxel in the mask). The cost alone cannot tell a stalled level: it keeps "
        "creeping down while the field has stopped moving. 0 = always run -miter iterations. Small steps can still add up, so "
        "check the per-level lines before relying on it.",
    )
    sched.add_argument(
        "-reg_mode",
        choices=("bending", "membrane"),
        default="bending",
        help="Field regularisation model.",
    )
    sched.add_argument(
        "-no_ssqlambda",
        action="store_true",
        help="Do not scale the penalty weight by the current SSD each iteration.",
    )
    sched.add_argument(
        "-pe_shift",
        action="store_true",
        help="EXPERIMENTAL: first estimate + remove a single global PE-axis translation "
        "between the two scans (tiny scanner shift), then estimate the field. A rigid "
        "shift is confounded by the field itself, so it is capped small; off by default.",
    )
    sched.add_argument(
        "-pad_phase_wrap",
        default="0",
        metavar="N | S1,S2",
        help="Handle tissue that distortion pushed past the phase-encode edge of the FOV, "
        "where it aliases in at the other end. Without this the solver matches that wrapped "
        "signal where it landed and pulls the wrong end of the brain.\n"
        "  N (one unsigned number): pad every scan by N voxels at both PE ends with slices "
        "wrapped from the opposite end.\n"
        "  S1,S2 (one signed number per scan, blip_up first; also '-5 +5'): say where each "
        "scan's wrap belongs. The sign is the direction the wrapped slab MOVES, in "
        "anatomical terms, whatever the storage order: +K takes the K slices at the "
        "left/posterior/inferior end and moves them beyond the right/anterior/superior end; "
        "-K the reverse; 0 leaves the scan. For an A/P phase encode, +9 = 'the back of the "
        "brain wrapped to the front; put it back behind the front'. All scans are then "
        "zero-padded onto one grid. E.g. -5,0 when only blip_up wrapped.\n"
        "The amount is data-dependent -- try a few, the run prints which anatomical ends "
        "each move goes between. The estimate is cropped back to the input grid; applying "
        "the saved warp with ffs_nwarp does not wrap.",
    )

    sched.add_argument(
        "-pad_phase_empty",
        choices=("zero", "unknown"),
        default="zero",
        help="How the cost treats voxels a signed -pad_phase_wrap emptied (the moved slab's "
        "old place, and zero padding added for the other scan). zero: they are measured "
        "zeros, so pushing tissue into them costs something. unknown: they are left out "
        "of the cost like missing data -- which makes them a blind zone the field can dump "
        "mismatched tissue into (seen as frontal tissue squashed against the FOV edge). "
        "A scan's own all-zero edge planes are always unknown.",
    )
    sched.add_argument(
        "-save_pad_phase",
        action="store_true",
        help="Write {prefix}_padphase: the inputs after -pad_phase_wrap, one volume per "
        "scan, on the padded grid the field is estimated on (header origin moved so it "
        "overlays the inputs). Check that each wrapped slab landed where it belongs.",
    )

    mot = parser.add_argument_group("Movement (topup --estmov analogue)")
    mot.add_argument(
        "-estmov",
        "-motion",
        action="store_true",
        help="Jointly estimate rigid head movement between the scans. "
        "Movement is estimated block-coordinate with the field at the COARSE levels only "
        "(knot spacing >= 10 mm, reproducing topup's --estmov schedule) and frozen for the "
        "fine levels; the first scan is the fixed reference and the PE-axis translation "
        "(degenerate with the field) is excluded. Reuses ffs_moco's GPU rigid registration "
        "on the field-corrected images. Off by default (assumes the pair is aligned).",
    )
    mot.add_argument(
        "-motion_ref",
        type=int,
        default=0,
        help="Index of the fixed reference scan for movement (default 0, the first).",
    )
    mot.add_argument(
        "-motion_interp",
        default="cubic",
        choices=("linear", "cubic", "quintic", "heptic", "wsinc5"),
        help="Interpolation used when baking the estimated rigid transform into the data.",
    )

    fold = parser.add_argument_group("Anti-fold barrier (keeps the field diffeomorphic)")
    fold.add_argument(
        "-jac_penalty",
        "-jac-penalty",
        type=float,
        default=1e-3,
        help="Weight of the anti-fold barrier that forbids a negative Jacobian (a fold is "
        "physically impossible for a real blip pair). Relative to the data SSD, like -lambda. "
        "Set 0 to disable. Default reaches a positive min-Jacobian while changing the field "
        "only ~3 Hz (below the float32/64 noise floor).",
    )
    fold.add_argument(
        "-jac_floor",
        "-jac-floor",
        type=float,
        default=0.1,
        help="Jacobian margin: the barrier keeps the Jacobian in [floor, 2-floor].",
    )
    fold.add_argument(
        "-no_antifold",
        action="store_true",
        help="Disable the anti-fold barrier entirely (equivalent to -jac_penalty 0).",
    )
    fold.add_argument(
        "-reject_folds",
        action="store_true",
        help="Additionally veto any line-search step that introduces a fold. Off by default: "
        "it perturbs the field far more than the barrier for no extra fold removal.",
    )

    misc = parser.add_argument_group("Misc")
    misc.add_argument(
        "-precision",
        choices=("float32", "float64"),
        default="float32",
        help="Working precision of the solve. float32 is ~2x faster on consumer GPUs with "
        "no accuracy cost here (the sensitive reductions accumulate in float64 anyway); "
        "float64 reproduces the original all-double behaviour.",
    )
    add_device_arg(
        misc,
        extra="Use CPU on Mac: the stable CG reductions require float64, which MPS does not support.",
    )
    misc.add_argument("-verb", type=int, default=1, help="Verbosity (0/1/2).")
    add_warp_movie_args(parser, overlay=False)
    add_batch_args(
        parser,
        tool="ffs_blipflip",
        what="fieldmap solves",
        example="-blip_up up.nii.gz -blip_down down.nii.gz -pe_dir j -prefix dc",
        skip_note="-prefix (its _warp and _unwarped images)",
    )
    return parser


def _load_volume(path: str, collapse: str) -> tuple[torch.Tensor, np.ndarray, object]:
    """Load a NIfTI, collapse 4-D -> 3-D, return (nz,ny,nx) tensor + affine + header."""
    from fastfuncstuff.io.afni import load_nifti

    img = load_nifti(path)
    arr = np.asarray(img.dataobj, dtype=np.float32)  # (nx, ny, nz[, t])
    if arr.ndim == 4:
        arr = np.median(arr, axis=3) if collapse == "median" else arr.mean(axis=3)
    elif arr.ndim != 3:
        raise ValueError(f"{path}: expected 3-D or 4-D, got shape {arr.shape}")
    # (nx,ny,nz) -> (nz,ny,nx) tensor order used throughout processing.topup.
    t = torch.from_numpy(np.ascontiguousarray(arr.transpose(2, 1, 0)))
    return t, np.asarray(img.affine), img.header


def _voxel_sizes_zyx(affine: np.ndarray) -> tuple[float, float, float]:
    vx, vy, vz = (float(np.linalg.norm(affine[:3, i])) for i in range(3))
    return (vz, vy, vx)  # (vz, vy, vx) to match (nz, ny, nx) data


# Each tier is one call to make_ladder with different endpoints: more levels, a coarser
# start, a finer final knot spacing and a lower final regularisation buy a more precise
# field at increasing cost. See the ladder docstring for what each knob means.
_PRESETS: dict[str, dict] = {
    # Default. Whole-head down to 4 mm knots with two refinement levels.
    "standard": dict(n_levels=9),
    # Three levels, stopping at 8 mm knots: enough for a smooth whole-head field,
    # not enough to resolve frontal/temporal detail. For a quick look.
    "quick": dict(n_levels=3, res_final=8.0, n_refine=0, lam_final=1e-5, miter_final=10),
    # Coarser start and a longer descent for high-field data, where the field is both
    # larger in amplitude and richer in structure. Penalty 1000x lower at every level and
    # twice the iterations: at standard's lambda the coarse levels settle on a nearly flat
    # field and cannot make the large shifts, which is what they exist for (on a real
    # pair, lowering lambda fixed what more iterations had not).
    "workhard": dict(
        n_levels=12,
        res_start=30.0,
        lam_start=5e-7,
        lam_final=1e-14,
        miter_scale=2,
    ),
    # As above but pushed to 2 mm knots -- only meaningful for sub-2 mm voxels, and the
    # low final lambda leans on the fold barrier to stay diffeomorphic. Same 1000x lower
    # lambda and doubled iterations as workhard, so the two tiers stay comparable.
    "superhard": dict(
        n_levels=14,
        res_start=30.0,
        res_final=2.0,
        lam_start=5e-7,
        lam_final=1e-16,
        miter_final=30,
        miter_scale=2,
    ),
}


def _fmt_list(vals, kind: str) -> str:
    if kind == "lam":
        return ",".join(f"{v:.3g}" for v in vals)
    return ",".join(f"{v:g}" for v in vals)


def _schedule_flags(cfg, indent: str) -> str:
    """The schedule as command-line flags, one per line, so a line can be copied and edited."""
    rows = [
        ("-warpres", cfg.warpres, ""),
        ("-fwhm", cfg.fwhm, ""),
        ("-lambda", cfg.lam, "lam"),
        ("-miter", cfg.miter, ""),
    ]
    return "\n".join(f"{indent}{flag:<9}{_fmt_list(v, kind)}" for flag, v, kind in rows)


def _schedule_epilog() -> str:
    lines = [
        "SCHEDULE PRESETS",
        "  Every schedule flag takes one value per level; copy a line, edit an element. A",
        "  single value applies to every level (-miter 30). A list you pass replaces that",
        "  list of the chosen -config tier, so its length must match the tier's level count.",
        "  -subsamp is 1 at every level in every tier.",
    ]
    for name in _PRESETS:
        cfg = _build_config(name)
        tag = "default, " if name == "standard" else ""
        lines += [
            "",
            f"  -config {name}  ({tag}{cfg.n_levels()} levels)",
            _schedule_flags(cfg, "    "),
        ]
    return "\n".join(lines)


def _build_config(name: str):
    """Return the TopupConfig for a preset name (see ``_PRESETS``)."""
    from fastfuncstuff.processing.topup import TopupConfig, make_ladder

    lad = make_ladder(**_PRESETS.get(name, _PRESETS["standard"]))
    return TopupConfig(
        warpres=lad.warpres,
        fwhm=lad.fwhm,
        lam=lad.lam,
        miter=lad.miter,
        subsamp=[1] * len(lad.warpres),
    )


def _resolve_device(device_spec) -> torch.device:
    """Device for a blipflip run: auto falls back to CPU without CUDA, and MPS is
    refused outright (the CG reductions are float64)."""
    if (
        device_spec is None or str(device_spec).lower() == "auto"
    ) and not torch.cuda.is_available():
        device_spec = "cpu"
    device = setup_device(device_spec, tf32=REGISTRATION_TF32)
    if device.type == "mps":
        raise SystemExit(
            "ffs_blipflip: MPS cannot run the required float64 CG reductions; "
            "use -device cpu on Mac."
        )
    return device


def _expected_outputs(args: argparse.Namespace) -> list[str]:
    """Concrete output paths a solo run of ``args`` would write, for -batch_skip.

    The warp is the estimate; the unwarped stack is checked with it because the
    cross-fmap stage reads that, not the warp."""
    if not args.prefix:
        return []
    pinfo = parse_prefix(args.prefix)
    outs = [f"{pinfo.stem}_warp{pinfo.nifti_ext}"]
    if not args.no_unwarped:
        outs.append(f"{pinfo.stem}_unwarped{pinfo.nifti_ext}")
    if getattr(args, "save_pad_phase", False):
        outs.append(f"{pinfo.stem}_padphase{pinfo.nifti_ext}")
    movie = resolve_movie_path(args)
    if movie is not None:
        outs.append(movie)
    return outs


def _validate_batch_run(run_args: argparse.Namespace) -> None:
    """Per-run validation for a batch job: the flags argparse would have enforced."""
    missing = [f for f in ("pe_dir", "prefix") if not getattr(run_args, f, None)]
    if missing:
        raise ValueError("run is missing " + ", ".join("-" + m for m in missing))


_SIGNED_LIST = re.compile(r"^[+-]?\d+(,[+-]?\d+)*,?$")


def _join_signed_values(argv: list[str]) -> list[str]:
    """Fold the values after -pad_phase_wrap into one ``flag=value`` token.

    argparse reads ``-5,+5`` as an unknown flag, and ``-5 +5`` as two positionals, so
    the signed per-scan form would never reach the option otherwise.
    """
    out: list[str] = []
    i = 0
    while i < len(argv):
        tok = argv[i]
        if tok.lstrip("-").replace("-", "_") == "pad_phase_wrap":
            vals = []
            while i + 1 < len(argv) and _SIGNED_LIST.match(argv[i + 1]):
                i += 1
                vals.append(argv[i].strip(","))
            out.append(f"{tok}={','.join(vals)}" if vals else tok)
        else:
            out.append(tok)
        i += 1
    return out


def _parse_phase_wrap(spec: str, n_scans: int) -> tuple[int, list[int] | None]:
    """``-pad_phase_wrap`` -> (symmetric wrap padding, per-scan unwrap shifts or None)."""
    tokens = [t for t in spec.replace(",", " ").split() if t]
    if len(tokens) == 1 and tokens[0][0] not in "+-":
        n = int(tokens[0])
        if n < 0:
            raise SystemExit("ffs_blipflip: -pad_phase_wrap N must be >= 0")
        return n, None
    if len(tokens) != n_scans:
        raise SystemExit(
            f"ffs_blipflip: -pad_phase_wrap needs one unsigned number, or one signed shift per "
            f"scan ({n_scans}); got {spec!r}"
        )
    return 0, [int(t) for t in tokens]


def _pe_ends(affine: np.ndarray, nifti_axis: int) -> tuple[str, str]:
    """Anatomical names of the (low-index, high-index) ends of a voxel axis."""
    col = np.asarray(affine)[:3, nifti_axis]
    world = int(np.argmax(np.abs(col)))
    towards = "RAS"[world] if col[world] > 0 else "LPI"[world]
    away = {"R": "L", "L": "R", "A": "P", "P": "A", "S": "I", "I": "S"}[towards]
    names = {
        "R": "right",
        "L": "left",
        "A": "anterior",
        "P": "posterior",
        "S": "superior",
        "I": "inferior",
    }
    return names[away], names[towards]


def _anatomical_moves_to_index_shifts(
    moves: list[int], pe_axes: list[int], affine: np.ndarray
) -> list[int]:
    """``-pad_phase_wrap`` shifts (+ moves the slab toward R/A/S) -> ``unwrap_pe`` shifts
    (negative moves the low-index slab past the high-index end)."""
    shifts = []
    for k, axis in zip(moves, pe_axes, strict=True):
        _, high = _pe_ends(affine, axis)
        shifts.append(-k if high in ("right", "anterior", "superior") else k)
    return shifts


def main(argv: list[str] | None = None) -> int:
    argv = _join_signed_values(list(sys.argv[1:] if argv is None else argv))
    args = create_parser().parse_args(argv)

    if args.batch is not None or args.batch_run:
        # A fieldmap solve is seconds of GN on a B-spline field wrapped in ~2s of
        # interpreter/CUDA startup, and a session has one per blip-up/down pair.
        run_batch_jobs(
            tool="ffs_blipflip",
            jobs=collect_batch_jobs(args.batch, args.batch_run),
            device=_resolve_device(args.device),
            parse_line=lambda line, base: create_parser().parse_args(
                _join_signed_values(shlex.split(line)), base
            ),
            defaults=args,
            dispatch=_dispatch_raising,
            validate=_validate_batch_run,
            is_nested=lambda ra: ra.batch is not None or ra.batch_run is not None,
            expected_outputs=_expected_outputs,
            skip_existing=args.batch_skip,
        )
        return 0

    try:
        _validate_batch_run(args)
    except ValueError as exc:
        print(f"ERROR: {exc} (or use -batch FILE / -batch_run ARGS).", file=sys.stderr)
        return 2

    return _dispatch_run(args, _resolve_device(args.device))


def _dispatch_raising(args: argparse.Namespace, device: torch.device) -> None:
    rc = _dispatch_run(args, device)
    if rc:
        raise ValueError(f"run exited {rc}")


def _dispatch_run(args: argparse.Namespace, device: torch.device) -> int:
    """Solve one blip-up/down pair (the whole per-fieldmap body).

    Both the standalone path and every batch job go through here, so a manifest
    line reproduces a solo invocation bit-for-bit."""
    from fastfuncstuff.processing import topup as T
    from fastfuncstuff.processing.io import save_warp_field
    from fastfuncstuff.processing.medic import PE_AXIS_MAP, invert_displacement_pe

    pinfo = parse_prefix(args.prefix)
    stem, ext = pinfo.stem, pinfo.nifti_ext

    # ---- assemble the image list + geometry ----
    if args.imain:
        paths = list(args.imain)
        if len(paths) < 2:
            print("ffs_blipflip: -imain needs at least two images.", file=sys.stderr)
            return 2
    else:
        if not (args.blip_up and args.blip_down):
            print("ffs_blipflip: provide -blip_up and -blip_down, or -imain.", file=sys.stderr)
            return 2
        paths = [args.blip_up, args.blip_down]

    def _broadcast(vals: list, n: int, what: str) -> list:
        if len(vals) == 1:
            return vals * n
        if len(vals) != n:
            raise SystemExit(f"ffs_blipflip: {what} needs 1 or {n} values, got {len(vals)}")
        return vals

    pe_dirs = _broadcast(args.pe_dir, len(paths), "-pe_dir")
    # Readout is optional: absent -> use 1.0 (warp unaffected by a common factor) and force
    # the Hz field map off, since without a real readout the field is in voxels, not Hz.
    no_readout = args.readout is None
    readouts = (
        [1.0] * len(paths) if no_readout else _broadcast(args.readout, len(paths), "-readout")
    )

    # For the plain pair form, -pe_dir describes blip_up; blip_down is opposite.
    if not args.imain and len(args.pe_dir) == 1:
        up = args.pe_dir[0]
        down = up[:-1] if up.endswith("-") else up + "-"
        pe_dirs = [up, down]

    scans: list[T.ScanSpec] = []
    affine = None
    header = None
    for p, pe, ro in zip(paths, pe_dirs, readouts, strict=True):
        if pe not in PE_AXIS_MAP:
            raise SystemExit(f"ffs_blipflip: bad -pe_dir '{pe}'")
        data, aff, hdr = _load_volume(p, args.collapse)
        if affine is None:
            affine, header = aff, hdr
        sign = -1.0 if pe.endswith("-") else 1.0
        scans.append(
            T.ScanSpec(data=data.to(device), pe_axis=PE_AXIS_MAP[pe], sign=sign, readout=float(ro))
        )
    assert affine is not None
    vox = _voxel_sizes_zyx(affine)

    # ---- schedule ----
    cfg = _build_config(args.config)
    # -warpres first: a full knot list sets the level count the other lists broadcast to.
    for name in ("warpres", "fwhm", "lam", "miter", "subsamp"):
        vals = getattr(args, name)
        if vals:
            setattr(cfg, name, list(vals) * cfg.n_levels() if len(vals) == 1 else list(vals))
    flags = {"warpres": "-warpres", "fwhm": "-fwhm", "lam": "-lambda", "miter": "-miter"}
    flags["subsamp"] = "-subsamp"
    bad = [
        f"{flags[k]} ({len(getattr(cfg, k))})"
        for k in flags
        if len(getattr(cfg, k)) != cfg.n_levels()
    ]
    if bad:
        print(
            f"ffs_blipflip: the schedule has {cfg.n_levels()} levels (-warpres) but "
            f"{', '.join(bad)} do not; give one value per level, or a single value",
            file=sys.stderr,
        )
        return 2
    cfg.min_update_vox = args.min_update
    cfg.reg_mode = args.reg_mode
    cfg.ssqlambda = not args.no_ssqlambda
    cfg.jac_penalty = 0.0 if args.no_antifold else args.jac_penalty
    cfg.jac_floor = args.jac_floor
    cfg.reject_folds = args.reject_folds

    if args.verb >= 1:
        print(
            f"ffs_blipflip: {len(scans)} scans, grid={tuple(scans[0].data.shape)}, "
            f"voxel(zyx)={tuple(round(v, 3) for v in vox)} mm, device={device}, "
            f"precision={args.precision}"
        )
        print(f"  schedule '{args.config}': {cfg.n_levels()} levels, as run:")
        print(_schedule_flags(cfg, "    "))
        print(f"    -min_update {cfg.min_update_vox:g}")
        if no_readout:
            print("  no -readout given: field map (Hz) disabled; warp is unaffected.")

    if args.estmov and not (0 <= args.motion_ref < len(scans)):
        print(f"ffs_blipflip: -motion_ref {args.motion_ref} out of range.", file=sys.stderr)
        return 2

    # One movie row per scan; run_topup swaps in its rescaled/shifted working copies.
    recorder = build_warp_movie_recorder(
        args,
        None,
        [sc.data for sc in scans],
        affine,
        device,
        "blipflip",
        row_labels=(
            [f"scan {i + 1} ({pe})" for i, pe in enumerate(pe_dirs)]
            if args.imain
            else [f"blip_up ({pe_dirs[0]})", f"blip_down ({pe_dirs[1]})"]
        ),
    )
    wrap_pad, moves = _parse_phase_wrap(args.pad_phase_wrap, len(scans))
    unwrap = None
    if moves is not None:
        # The flag speaks anatomy (+ moves the slab toward R/A/S); unwrap_pe speaks index
        # order (shift < 0 moves the low-index slab past the high end). Storage order is
        # per-file, so map through the affine -- reading the sign as index order put the
        # air in front of the head behind the occipital pole on an A>P-stored scan.
        unwrap = _anatomical_moves_to_index_shifts(moves, [sc.pe_axis for sc in scans], affine)
        for i, (k, sc) in enumerate(zip(moves, scans, strict=True)):
            low, high = _pe_ends(affine, sc.pe_axis)
            index_points_positive = high in ("right", "anterior", "superior")
            if args.verb >= 1 and k != 0:
                neg_end, pos_end = (low, high) if index_points_positive else (high, low)
                src, dst = (neg_end, pos_end) if k > 0 else (pos_end, neg_end)
                print(
                    f"  unwrap scan {i + 1} ({pe_dirs[i]}): {abs(k)} slices at the {src} end "
                    f"-> beyond the {dst} end"
                )
    elif args.verb >= 1 and wrap_pad:
        print(f"  wrap padding: {wrap_pad} voxels at both phase-encode ends")
    if args.save_pad_phase:
        padded, pad_tdims, front, _ = T.pad_scans_pe(scans, wrap_pad, unwrap)
        pad_affine = np.array(affine, dtype=float, copy=True)
        for d in pad_tdims:
            # Voxel index grew by `front` on this axis; move the origin back by as much.
            axis = {2: 0, 1: 1, 0: 2}[d]
            pad_affine[:3, 3] -= front * pad_affine[:3, axis]
        pad_path = f"{stem}_padphase{ext}"
        _save_zyx(pad_path, torch.stack(padded, dim=-1), pad_affine)
        if args.verb >= 1:
            print(
                f"  wrote {pad_path}  (inputs as estimated: {tuple(padded[0].shape[::-1])}, one volume per scan)"
            )

    solve_dtype = torch.float64 if args.precision == "float64" else torch.float32
    result = T.run_topup(
        scans,
        vox,
        cfg,
        pe_shift=args.pe_shift,
        wrap_pad=wrap_pad,
        unwrap=unwrap,
        empty_as_zero=args.pad_phase_empty == "zero",
        progress=args.verb >= 1,
        solve_dtype=solve_dtype,
        mask_field=not args.no_mask_field,
        estimate_motion=args.estmov,
        motion_ref=args.motion_ref,
        motion_interp=args.motion_interp,
        recorder=recorder,
    )

    # ---- outputs ----
    # Choose the scan whose geometry the warp corrects.
    ref_idx = 0 if args.warp_for == "up" else (1 if len(scans) > 1 else 0)
    ref = scans[ref_idx]
    pe_tdim = T._NIFTI_AXIS_TO_TDIM[ref.pe_axis]

    # Geometric undistortion warp. Our forward model (like topup's update()) recovers
    # the undistorted image by resampling the scan at index + disp, so the pull warp
    # used by ffs_nwarp (output(i) = source(i + warp)) IS +disp — no inversion. This maps
    # the reference (distorted) geometry INTO the undistorted "middle" space.
    disp_forward = result.field_hz * (ref.readout * ref.sign)
    pull = disp_forward
    if args.pe_shift and result.pe_shift_vox != 0.0:
        # The reference scan was pre-shifted by +/- shift/2 (scan0 +, scan1 -); fold that
        # constant PE translation into the warp so it corrects the raw (unshifted) input.
        half = result.pe_shift_vox * (0.5 if ref_idx == 0 else -0.5)
        pull = pull + half

    def _save_pe_warp(disp_pe: torch.Tensor, path: str) -> None:
        """Save a single 4-D mm warp whose only nonzero component is on the PE axis."""
        z = torch.zeros_like(disp_pe)
        comps = [z, z, z]  # x, y, z slots, each (nz,ny,nx)
        comps[{0: 0, 1: 1, 2: 2}[ref.pe_axis]] = disp_pe
        save_warp_field(
            comps[0],
            comps[1],
            comps[2],
            path,
            header_info={"affine": affine, "header": header},
            units="mm",
        )

    warp_path = f"{stem}_warp{ext}"
    _save_pe_warp(pull, warp_path)
    if args.verb >= 1:
        print(f"  wrote {warp_path}  (distorted[{pe_dirs[ref_idx]}] -> undistorted 'middle')")

    if not args.no_invwarp:
        # Inverse: undistorted 'middle' -> distorted (forward) geometry, the 1-D PE inverse.
        invwarp = invert_displacement_pe(pull, pe_tdim)
        invwarp_path = f"{stem}_invwarp{ext}"
        _save_pe_warp(invwarp, invwarp_path)
        if args.verb >= 1:
            print(
                f"  wrote {invwarp_path}  (undistorted 'middle' -> distorted[{pe_dirs[ref_idx]}])"
            )

    if not args.no_fmap and not no_readout:
        _save_zyx(f"{stem}_field{ext}", result.field_hz, affine)
        if args.verb >= 1:
            print(f"  wrote {stem}_field{ext}  (off-resonance field, Hz)")

    if not args.no_unwarped:
        undist = torch.stack(result.unwarped, dim=0)  # (S, nz, ny, nx)
        _save_zyx(f"{stem}_unwarped{ext}", undist.movedim(0, -1), affine)  # (nz,ny,nx,S)
        _save_zyx(f"{stem}_mean{ext}", result.mean_unwarped, affine)
        if args.verb >= 1:
            print(f"  wrote {stem}_unwarped{ext}, {stem}_mean{ext}")
    # Jacobian intensity-modulation map. A negative Jacobian means the displacement
    # gradient dropped below -1, i.e. the warp folded over (non-diffeomorphic) --
    # those voxels invert intensity and show up as streaks. Warn regardless of -no_jac;
    # a nonzero fold fraction is a quality signal that the field over-fit (too fine a
    # knot spacing / too little regularisation, e.g. -superhard on modest data).
    jac = T._jacobian_pe(disp_forward, pe_tdim)
    neg_frac = float((jac < 0).float().mean())
    if neg_frac > 0 and args.verb >= 0:
        hint = (
            "raise -jac_penalty (anti-fold barrier)"
            if not args.no_antifold
            else "drop -no_antifold to enable the anti-fold barrier"
        )
        print(
            f"  WARNING: Jacobian is negative in {100 * neg_frac:.3f}% of voxels "
            f"(min {float(jac.min()):.2f}) -- the warp folds there (non-diffeomorphic); "
            f"expect intensity streaks. A real blip pair cannot fold, so {hint}."
        )
    if not args.no_jac:
        _save_zyx(f"{stem}_jac{ext}", jac, affine)
        if args.verb >= 1:
            print(f"  wrote {stem}_jac{ext}")

    # Estimated rigid movement parameters (topup's movpar analogue): one row per scan,
    # decomposed to dx dy dz (voxels) rz rx ry (degrees) in the ffs_moco convention.
    if args.estmov:
        from fastfuncstuff.processing.affine import matrix_to_params

        movpar_path = f"{stem}_movpar.txt"
        rows = []
        for mat in result.motion_matrices:
            p = matrix_to_params(mat.float())[:6].tolist()
            rows.append("  ".join(f"{v:+.6f}" for v in p))
        with open(movpar_path, "w") as fh:
            fh.write("# dx dy dz (vox)  rz rx ry (deg); one row per scan; scan 0 = reference\n")
            fh.write("\n".join(rows) + "\n")
        if args.verb >= 1:
            print(f"  wrote {movpar_path}  (per-scan rigid movement)")

    render_warp_movie(recorder, args, args.verb)

    pe_letter = {0: "i", 1: "j", 2: "k"}[ref.pe_axis]
    if args.verb >= 1:
        print(f"Done: {datetime.now():%Y-%m-%d %H:%M:%S}")
        print(
            f"  apply:  ffs_nwarp -source epi{ext} -master epi{ext} "
            f"-nwarp {warp_path} -jac {pe_letter} -prefix epi_dc{ext}"
        )
        print("          (-jac applies the phase-encode Jacobian intensity correction)")
    return 0


def _save_zyx(path: str, vol_zyx: torch.Tensor, affine: np.ndarray) -> None:
    """Save a (nz,ny,nx[,...]) tensor as NIfTI (nx,ny,nz[,...])."""
    from fastfuncstuff.io.afni import save_nifti

    arr = vol_zyx.detach().cpu().numpy()
    if arr.ndim == 3:
        arr = arr.transpose(2, 1, 0)
    elif arr.ndim == 4:
        arr = arr.transpose(2, 1, 0, 3)
    save_nifti(np.ascontiguousarray(arr.astype(np.float32)), path, affine=affine)


if __name__ == "__main__":
    sys.exit(main())
