"""Trial bookkeeping for `ffs_tunewarp`: what was tried, what it scored, how to redo it.

Two constraints shape this, and they pull against each other:

* **Space cannot dominate.** A full search is hundreds of fits, and a warp field
  on a 193^3 grid is ~90 MB — keeping them all is hundreds of gigabytes for
  numbers that fit in a spreadsheet. So by default a trial's outputs are scored
  and then deleted, and only the scores survive.
* **Eyeballs are the final judge.** No consensus rank replaces looking at the
  thing. So any trial must be re-runnable on demand: "make me number 7 again,
  and keep it this time."

The resolution is that the store records the *exact command* that produced each
trial, and reproducing a trial re-runs that command with outputs kept. The
command is generated by the same `tunespec.render_command` that ran it, so what
you reproduce is what ran, not a reconstruction of it.
"""

from __future__ import annotations

import datetime
import json
import statistics
from collections.abc import Sequence
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import Any

from .warpqc import FAIL, MARGINAL, PASS

GRADE_ORDER = {PASS: 0, MARGINAL: 1, FAIL: 2}


@dataclass
class Trial:
    """One backend + config + subject fit, scored and then thrown away."""

    trial_id: int
    config_id: int
    backend: str
    subject: str
    config: dict[str, Any]
    command: list[str]
    seconds: float = 0.0
    scores: dict[str, float] = field(default_factory=dict)
    grade: str = PASS
    reasons: list[str] = field(default_factory=list)
    warpqc: dict[str, Any] = field(default_factory=dict)
    # Continuous distance from the regularity gate, > 0 == passing. The grade is
    # what a user reads; this is what the adaptive searcher steers by, because a
    # label carries no gradient and this boundary is a cliff.
    margin: float = 0.0
    # Per-level convergence telemetry (formwarp.LevelStats.as_dict()). Answers the
    # question the iteration knobs raise but cannot settle on their own: was this
    # config starved of iterations, or did it over-run and fall back?
    levels: list[dict[str, Any]] = field(default_factory=list)
    kept_outputs: str | None = None  # set when a trial was reproduced

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass
class ConfigResult:
    """One config, aggregated over the subjects it was fit on.

    The aggregate is deliberately conservative: the grade is the *worst* grade
    any subject produced, because a setting that folds on one brain out of three
    is not a setting that works. The spread across subjects is reported rather
    than hidden — it is how you tell "we found something" from "we found noise",
    and a parameter in the middle of a wide-but-consistent spread is often the
    right default.
    """

    config_id: int
    backend: str
    config: dict[str, Any]
    n_subjects: int
    score_mean: float
    score_spread: float
    grade: str
    reasons: list[str]
    seconds_mean: float

    def label(self) -> str:
        if not self.config:
            return "(defaults)"
        return " ".join(f"{k}={v}" for k, v in sorted(self.config.items()))


class TrialStore:
    """Append-only record of every trial, persisted as JSON."""

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.trials: list[Trial] = []
        self._next_trial = 0
        self._config_ids: dict[str, int] = {}
        if self.path.exists():
            self.load()

    # --- identity -----------------------------------------------------------

    def config_id(self, backend: str, config: dict[str, Any]) -> int:
        """Stable id for a (backend, config) pair, so subjects aggregate."""
        key = backend + "|" + json.dumps(config, sort_keys=True, default=str)
        if key not in self._config_ids:
            self._config_ids[key] = len(self._config_ids) + 1
        return self._config_ids[key]

    # --- recording ----------------------------------------------------------

    def add(
        self,
        backend: str,
        subject: str,
        config: dict[str, Any],
        command: list[str],
        **outcome: Any,
    ) -> Trial:
        self._next_trial += 1
        t = Trial(
            trial_id=self._next_trial,
            config_id=self.config_id(backend, config),
            backend=backend,
            subject=subject,
            config=dict(config),
            command=list(command),
            **outcome,
        )
        self.trials.append(t)
        return t

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(
                {
                    "config_ids": self._config_ids,
                    "trials": [t.as_dict() for t in self.trials],
                },
                indent=2,
                default=str,
            )
        )

    def load(self) -> None:
        raw = json.loads(self.path.read_text())
        self._config_ids = raw.get("config_ids", {})
        # Ignore fields this version does not know about, so a table written by a
        # newer build still opens. A tuning run is expensive; losing one to a
        # schema addition would be the worst possible time to be strict.
        known = {f.name for f in fields(Trial)}
        self.trials = [Trial(**{k: v for k, v in t.items() if k in known}) for t in raw["trials"]]
        self._next_trial = max((t.trial_id for t in self.trials), default=0)

    # --- scoring ------------------------------------------------------------

    def compute_consensus(self, panel: Sequence[str]) -> None:
        """Fill in ``scores["consensus"]`` for every trial, using ``panel`` as the jury.

        Consensus is inherently *relative* — each functional votes by ranking the
        candidates it scored — so it cannot be computed when a trial is run, only
        once the field is known. Ranking happens **within a subject**, because a
        functional's absolute value varies more between brains than between the
        settings we are trying to separate; comparing raw values across subjects
        would measure the subjects.

        The panel comes from :func:`allcost.judge_panel` and is not merely "all
        the costs minus the optimised one": it also drops the functionals that
        are *meaningless* for the contrast regime. See that function for why —
        the short version is that on same-modality data three of the fourteen
        rank the worst warp first.
        """
        from .allcost import consensus_rank

        keep = set(panel)
        by_subject: dict[str, list[Trial]] = {}
        for t in self.trials:
            by_subject.setdefault(t.subject, []).append(t)

        for ts in by_subject.values():
            scored = {
                str(t.trial_id): {k: v for k, v in t.scores.items() if k in keep}
                for t in ts
                if t.scores
            }
            scored = {k: v for k, v in scored.items() if v}
            if not scored:
                continue
            ranks = dict(consensus_rank(scored))
            for t in ts:
                if str(t.trial_id) in ranks:
                    t.scores["consensus"] = ranks[str(t.trial_id)]

    # --- aggregation --------------------------------------------------------

    def results(self, score_key: str = "consensus") -> list[ConfigResult]:
        """Aggregate trials into per-config results, best first.

        Ordering puts every passing config above every marginal one and every
        marginal above every failing one, *then* sorts by score. A better
        similarity score never buys its way past a folded warp — that inversion
        is the whole failure mode this tool exists to prevent.
        """
        by_config: dict[int, list[Trial]] = {}
        for t in self.trials:
            by_config.setdefault(t.config_id, []).append(t)

        out = []
        for cid, ts in by_config.items():
            vals = [t.scores.get(score_key) for t in ts]
            vals = [v for v in vals if v is not None]
            if not vals:
                continue
            worst = max(ts, key=lambda t: GRADE_ORDER.get(t.grade, 3))
            out.append(
                ConfigResult(
                    config_id=cid,
                    backend=ts[0].backend,
                    config=ts[0].config,
                    n_subjects=len(ts),
                    score_mean=statistics.fmean(vals),
                    score_spread=statistics.pstdev(vals) if len(vals) > 1 else 0.0,
                    grade=worst.grade,
                    reasons=worst.reasons,
                    seconds_mean=statistics.fmean([t.seconds for t in ts]),
                )
            )
        out.sort(key=lambda r: (GRADE_ORDER.get(r.grade, 3), r.score_mean))
        return out

    # --- reproduction -------------------------------------------------------

    def commands_for(self, config_id: int) -> list[tuple[str, list[str]]]:
        """(subject, command) for every trial of a config — what to re-run."""
        return [(t.subject, t.command) for t in self.trials if t.config_id == config_id]


@dataclass
class KnobEffect:
    """What one parameter does, read off every trial that varied it.

    This is the output the tool exists to produce. Not "the best config for
    subject 3", but "raising this knob helps, on every brain we tried" — which
    is what a default can be built on.
    """

    backend: str
    key: str
    levels: list[tuple[Any, float, float, int]]  # (value, mean score, fold rate, n)
    consistency: float  # fraction of subjects agreeing with the pooled direction
    direction: str  # "lower is better" | "higher is better" | "flat"


def knob_effects(
    store: TrialStore, score_key: str = "consensus", pass_only: bool = True
) -> list[KnobEffect]:
    """Marginal effect of every knob, and how consistent it is across subjects.

    ``pass_only`` averages the score over trials that passed the regularity gate,
    which is not a detail. A folded warp scores *better* — that is what folding
    buys — so a level's mean over all trials is pulled down in proportion to how
    often it broke, and the report ends up recommending the setting that fails
    most. Fold rate is still counted over every trial, so the two columns answer
    the two different questions: "how good when it works" and "how often does it
    work". A level with no passing trials shows ``n/a``, which is the honest
    answer rather than a number that flatters it.

    Deliberately *not* a held-out-subject cross-validation. Nothing is being
    fitted to the subjects — a handful of discrete settings are being compared —
    so there is nothing to overfit and no reason to hold anything back. The
    generalization question here is simply whether a knob pushes the result the
    same way on every brain, and the honest way to answer that is to run them all
    and look at whether the direction agrees. Consistency is the statistic;
    holding out would only cost data.
    """
    by_knob: dict[tuple[str, str], list[Trial]] = {}
    for t in store.trials:
        for key in t.config:
            by_knob.setdefault((t.backend, key), []).append(t)

    out = []
    for (backend, key), ts in sorted(by_knob.items()):
        values = sorted({_hashable(t.config[key]) for t in ts}, key=_sort_key)
        if len(values) < 2:
            continue  # pinned, so it has no measurable effect here

        levels = []
        for v in values:
            sel = [t for t in ts if _hashable(t.config[key]) == v]
            usable = [t for t in sel if t.grade == PASS] if pass_only else sel
            scored = [t.scores[score_key] for t in usable if score_key in t.scores]
            folds = [t for t in sel if t.grade != PASS]
            levels.append(
                (
                    v,
                    statistics.fmean(scored) if scored else float("nan"),
                    len(folds) / len(sel) if sel else 0.0,
                    len(sel),
                )
            )

        # Pooled direction: does the best level sit low or high in the range?
        #
        # A level with no passing trial has no score, and dropping the whole knob
        # for that would hide precisely the most useful knob in the report: the
        # one with a fold cliff in it. So an unscoreable level still appears, with
        # its fold rate, and the direction is read off whatever did pass.
        finite = [(v, s) for v, s, _, _ in levels if s == s]
        if not finite:
            out.append(KnobEffect(backend, key, levels, 0.0, "never passes the gate"))
            continue
        best_v = min(finite, key=lambda p: p[1])[0]
        if len(finite) == 1:
            out.append(KnobEffect(backend, key, levels, 1.0, f"only {best_v} passes the gate"))
            continue
        lo, hi = finite[0][0], finite[-1][0]
        if best_v == lo:
            direction = "lower is better"
        elif best_v == hi:
            direction = "higher is better"
        else:
            direction = f"best near {best_v}"

        # Consistency: how many subjects put their own *marginal* best at the
        # same level. It must be marginal on both sides — comparing the pooled
        # marginal against each subject's best joint config compares two
        # different things and reports nonsense (a knob can look "higher is
        # better, 0% agree", which is incoherent), because the winning joint
        # config's level need not be the level that wins on average.
        per_subject: dict[str, dict[Any, list[float]]] = {}
        for t in ts:
            if pass_only and t.grade != PASS:
                continue
            if score_key in t.scores:
                lvl = _hashable(t.config[key])
                per_subject.setdefault(t.subject, {}).setdefault(lvl, []).append(
                    t.scores[score_key]
                )
        agree = 0
        for levels_for_subject in per_subject.values():
            marginals = {v: statistics.fmean(s) for v, s in levels_for_subject.items() if s}
            if marginals and min(marginals, key=lambda v: marginals[v]) == best_v:
                agree += 1
        consistency = agree / len(per_subject) if per_subject else 0.0

        out.append(KnobEffect(backend, key, levels, consistency, direction))
    return out


def _hashable(v: Any) -> Any:
    return tuple(v) if isinstance(v, list) else v


def _sort_key(v: Any) -> tuple:
    return (0, v, "") if isinstance(v, (int, float)) else (1, 0, str(v))


def format_knob_effects(effects: list[KnobEffect]) -> str:
    """Per-knob table: what each level scored, how often it folded, is it consistent."""
    if not effects:
        return "  (nothing varied yet)"
    lines = [
        "  score = mean over trials that PASSED the gate; not-PASS counts every trial.",
        "  'n/a' means no setting at that level ever produced a sound warp.",
        "",
    ]
    for e in effects:
        lines.append(
            f"  {e.backend}.{e.key}  -- {e.direction}, {e.consistency:.0%} of subjects agree"
        )
        lines.append(f"      {'value':>12s} {'score':>8s} {'not-PASS':>9s} {'n':>4s}")
        for v, score, fold, n in e.levels:
            s = f"{score:8.3f}" if score == score else "     n/a"
            lines.append(f"      {str(v):>12s} {s} {fold:8.0%} {n:4d}")
        lines.append("")
    return "\n".join(lines)


@dataclass
class IterationAdvice:
    """What the iteration ceiling for one backend level should be.

    Derived, not searched. The ceiling is not a quality knob with an interior
    optimum — too few is always wrong and too many is free — so laddering over it
    spends fits to answer a question whose direction is known in advance. What is
    genuinely unknown is *how many* a level actually uses, and that is a
    measurement: run with the ceiling set high and look at where the levels stopped.
    """

    backend: str
    level: int
    n: int
    p50_used: float
    p95_used: int
    max_used: int
    starved_frac: float
    ceiling: int  # what was allowed
    recommended: int

    # The knob to reach for when a level burns iterations rather than converging.
    # qwarp is absent on purpose: it optimises shrinking patches rather than taking
    # steps, so "step size" has no single analogue there.
    STEP_KNOB = {"formwarp": "-grad_step", "optiwarp": "-max_step"}

    @property
    def step_knob(self) -> str | None:
        family = "optiwarp" if self.backend.startswith("optiwarp") else self.backend
        return self.STEP_KNOB.get(family)

    @property
    def crawling(self) -> bool:
        """Using most of a deliberately generous ceiling.

        Early stopping not firing is not a failure of the stopping rule — it means
        the iterations were genuinely being used. But a level that needs hundreds of
        iterations to flatten is usually taking steps that are too small, so the
        useful response is a bigger step, not only a bigger ceiling.
        """
        return self.max_used > self.ceiling // 2

    @property
    def verdict(self) -> str:
        hint = f"; try a larger {self.step_knob}" if self.step_knob else ""
        if self.starved_frac > 0:
            return f"TOO LOW — {self.starved_frac:.0%} of fits cut off while improving{hint}"
        if self.crawling:
            return f"converging slowly ({self.max_used}/{self.ceiling}){hint}"
        if self.recommended < self.ceiling // 2:
            return "generous (fine — headroom is free)"
        return "about right"


def recommend_iterations(store: TrialStore, headroom: float = 2.0) -> list[IterationAdvice]:
    """Read the iteration ceiling back out of what the levels actually used.

    The recommendation is the worst observed *natural* stopping point with headroom,
    not the average: the ceiling has to accommodate the hardest subject, and the cost
    of it being too high is nothing while the cost of it being too low is a level
    silently truncated mid-improvement. Any level that was ever starved reports its
    own ceiling as a lower bound instead, because a truncated run cannot tell you how
    many iterations it would have used.
    """
    rows: dict[tuple[str, int], list[dict]] = {}
    for t in store.trials:
        for lev, stats in enumerate(t.levels):
            rows.setdefault((t.backend, lev), []).append(stats)

    out = []
    for (backend, lev), stats in sorted(rows.items()):
        used = sorted(s["iters_run"] for s in stats)
        caps = [s["n_iter_cap"] for s in stats]
        starved = sum(bool(s["starved"]) for s in stats) / len(stats)
        p95 = used[min(len(used) - 1, int(0.95 * (len(used) - 1)))]
        out.append(
            IterationAdvice(
                backend=backend,
                level=lev + 1,
                n=len(stats),
                p50_used=statistics.median(used),
                p95_used=p95,
                max_used=used[-1],
                starved_frac=starved,
                ceiling=max(caps),
                recommended=int(round(used[-1] * headroom)),
            )
        )
    return out


def format_iteration_advice(advice: list[IterationAdvice]) -> str:
    """The ceiling report: what each level used, and what to set it to."""
    if not advice:
        return "  (no iteration telemetry recorded)"
    lines = [
        "  Iteration ceilings, measured rather than searched. 'used' is where the level",
        "  actually stopped; the ceiling only has to be comfortably above the worst case.",
        "",
        f"  {'backend':16s} {'lvl':>3s} {'p50':>6s} {'p95':>6s} {'max':>6s} "
        f"{'cap':>6s} {'suggest':>8s}  verdict",
        "  " + "-" * 96,
    ]
    for a in advice:
        lines.append(
            f"  {a.backend:16s} {a.level:>3d} {a.p50_used:6.0f} {a.p95_used:6d} "
            f"{a.max_used:6d} {a.ceiling:6d} {a.recommended:8d}  {a.verdict}"
        )
    if any(a.starved_frac > 0 for a in advice):
        lines += [
            "",
            "  A starved level was still improving when its cap stopped it, so its 'used'",
            "  is a floor, not a measurement. Raise -iters and re-run to see the real number.",
        ]
    if any(a.crawling or a.starved_frac > 0 for a in advice):
        lines += [
            "",
            "  Where early stopping never fired, the iterations were genuinely needed — the",
            "  stopping rule is working. But needing most of a generous ceiling means the",
            "  solver is crawling, so raise the step size before raising the ceiling again.",
        ]
    return "\n".join(lines)


def format_export(store: TrialStore, recipe: str, subjects: str = "") -> str:
    """The run's conclusion as ``Preset`` source, ready to paste into tunespec.

    Deliberately printed for a human to commit rather than written to a file the
    tools read at runtime. A default changing is a real change: it should arrive as
    a reviewable diff with a provenance line attached, not appear because someone
    left a tuning directory lying around. The generated provenance is a starting
    point — the part only the operator knows is what the data actually was.
    """
    best: dict[str, ConfigResult] = {}
    for r in store.results():
        if r.grade == PASS and r.backend not in best:
            best[r.backend] = r
    if not best:
        return "  (no passing config to export — nothing here is fit to be a default)"

    n_subjects = len({t.subject for t in store.trials})
    n_fits = len(store.trials)
    lines = [
        "  Paste into PRESETS in fastfuncstuff/processing/tunespec.py.",
        "  Edit the provenance to say what the data actually was.",
        "",
    ]
    for backend, r in sorted(best.items()):
        cfg = ", ".join(f'"{k}": {v!r}' for k, v in sorted(r.config.items()))
        lines += [
            f'    ("{recipe}", "{backend}"): Preset(',
            f'        recipe="{recipe}",',
            f'        backend="{backend}",',
            f"        config={{{cfg}}},",
            "        provenance=(",
            f'            "{subjects or f"{n_subjects} subjects"}, {n_fits} fits, '
            f'{r.seconds_mean:.1f} s/fit, "',
            f'            "{datetime.date.today().isoformat()}."',
            "        ),",
            "    ),",
        ]
    lines += [
        "",
        "  Sanity-check before committing: a preset is a claim that these settings",
        "  generalize to data of this kind, which one run on one cohort cannot",
        "  establish on its own.",
    ]
    return "\n".join(lines)


def format_convergence(store: TrialStore) -> str:
    """Per backend and level: was it starved of iterations, or did it over-run?

    The iteration knobs cannot answer this from the score alone. A config at the top
    of the iters ladder might be there because more iterations genuinely help, or
    because the ladder is too short to show where it stops helping — and those call
    for opposite actions. ``best_iter`` separates them: a level that was still
    improving when the cap stopped it is starved, and one that peaked early and then
    ran on has iterations to give back.
    """
    rows: dict[tuple[str, int], list[dict]] = {}
    for t in store.trials:
        for lev, stats in enumerate(t.levels):
            rows.setdefault((t.backend, lev), []).append(stats)
    if not rows:
        return "  (no convergence telemetry recorded)"

    lines = [
        "  Per-level iteration behaviour. 'starved' = still improving at the cap, so",
        "  the ladder is too short; 'wasted' = iterations run after the kept one.",
        "",
        f"  {'backend':16s} {'lvl':>3s} {'iters':>6s} {'best@':>6s} {'wasted':>7s} "
        f"{'starved':>8s} {'damped':>7s} {'nolegal':>8s}  n",
        "  " + "-" * 88,
    ]
    for (backend, lev), stats in sorted(rows.items()):
        n = len(stats)
        lines.append(
            f"  {backend:16s} {lev + 1:>3d} "
            f"{statistics.fmean([s['iters_run'] for s in stats]):6.1f} "
            f"{statistics.fmean([s['best_iter'] for s in stats]):6.1f} "
            f"{statistics.fmean([s['wasted_iters'] for s in stats]):7.1f} "
            f"{sum(bool(s['starved']) for s in stats) / n:7.0%} "
            f"{sum(bool(s['damped_iters']) for s in stats) / n:6.0%} "
            f"{sum(bool(s.get('fold_fallback')) for s in stats) / n:7.0%}  {n}"
        )
    return "\n".join(lines)


def format_results_table(results: list[ConfigResult], limit: int = 25) -> str:
    """The table the user reads, and picks a number out of to reproduce."""
    if not results:
        return "  (no results yet)"
    lines = [
        f"  {'#':>3s}  {'backend':16s} {'score':>8s} {'+/-':>7s} {'grade':9s} {'s/fit':>6s}  settings",
        "  " + "-" * 104,
    ]
    for r in results[:limit]:
        lines.append(
            f"  {r.config_id:>3d}  {r.backend:16s} {r.score_mean:8.4f} "
            f"{r.score_spread:7.4f} {r.grade.upper():9s} {r.seconds_mean:6.1f}  {r.label()}"
        )
    if len(results) > limit:
        lines.append(f"  ... {len(results) - limit} more")
    lines.append("")
    lines.append("  Reproduce one with:  ffs_tunewarp ... -reproduce N   (keeps the outputs)")
    return "\n".join(lines)


def format_reproduce(store: TrialStore, config_id: int, out_dir: str | Path) -> str:
    """What re-running a config would do — the commands, verbatim."""
    cmds = store.commands_for(config_id)
    if not cmds:
        return f"No trial with config id {config_id}."
    out = Path(out_dir)
    lines = [f"Config {config_id}: {len(cmds)} fit(s), outputs kept in {out}/"]
    for subject, cmd in cmds:
        lines.append(f"  # {subject}")
        lines.append("  " + " ".join(cmd))
    return "\n".join(lines)
