"""Trial bookkeeping for `ffs_tunewarp`: what was tried, what it scored, how to redo it.

Two constraints shape this, and they pull against each other:

* **Space cannot dominate.** A full search is hundreds of fits, and a warp field
  on a 193^3 grid is ~90 MB — keeping them all is hundreds of gigabytes for
  numbers that fit in a spreadsheet. So by default a trial's outputs are scored
  and then deleted, and only the scores survive.
* **Eyeballs are the final judge.** No consensus rank replaces looking at the
  thing. So any trial must be re-runnable on demand: "make me number 7 again,
  and keep it this time."

The resolution is that the store records the *exact command* that produced each
trial, and reproducing a trial re-runs that command with outputs kept. The
command is generated by the same `tunespec.render_command` that ran it, so what
you reproduce is what ran, not a reconstruction of it.
"""

from __future__ import annotations

import datetime
import json
import statistics
from collections.abc import Sequence
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import Any

from .warpqc import (
    FAIL,
    MARGIN_LIMIT,
    MARGINAL,
    PASS,
    WarpQC,
    gate_margin,
    regularity_cautions,
    regularity_margin,
    regularity_verdict,
)

GRADE_ORDER = {PASS: 0, MARGINAL: 1, FAIL: 2}

# A config that clears the regularity gate by less than this many pooled
# between-subject sigmas is reported as NARROW and sorted below the clean passes.
#
# The unit matters more than the number. Clearance measured in *absolute* log
# units needs a constant nobody can defend; measured in units of how far the
# margin is observed to move when the same config is fit on a different brain,
# "narrow" means something checkable: the pass is a property of the subjects
# that happened to be drawn, not of the setting. Measured at 0.27 log units on
# T1->MNI, which is most of the whole passing range -- so this demotes more than
# it looks like it should, and that is the finding, not a mis-calibration.
NARROW_CLEARANCE_Z = 1.0
NARROW = "narrow"


BASELINE = "(baseline)"
"""Backend name for the do-nothing row: the input scored without any warp.

Every other number in a run is a rank among candidates, which says which setting
won but not whether *any* of them helped. The baseline is what turns the table
into a statement you can act on -- "nonlinear bought this much on data like this"
-- and it is the one row that has to be there for a recommendation to mean
anything.
"""


@dataclass
class RunMeta:
    """What produced a batch of trials: the code, the machine, and the data.

    Recorded because the trials alone are not interpretable later. Two runs of
    this tool are only comparable if the code that scored them agrees, and on
    2026-08-16 a fix to the qwarp Jacobian penalty changed every warp the engine
    produces -- silently invalidating every table written before it, with nothing
    in the file to say so. A stored commit turns that from a trap into a warning.

    The data fields exist for the same reason at a different timescale. A preset
    is a claim that some settings suit data *of a kind*, and "5 FreeSurfer brains"
    does not describe a kind: resolution, matrix and how much deformation was
    actually needed are what let the next person tell whether their data is like
    this one. See [[Data Variety]] for how wide that space is.
    """

    run_id: int
    started: str
    commit: str = "unknown"
    dirty: bool = False
    device: str = ""
    torch_version: str = ""
    recipe: str = ""
    contrast: str = ""
    optimize: str = ""
    panel: list[str] = field(default_factory=list)
    search: str = ""
    subjects: list[str] = field(default_factory=list)
    base: str = ""
    shape: tuple[int, ...] = ()
    voxdims: tuple[float, ...] = ()
    n_mask_voxels: int = 0
    note: str = ""

    def __post_init__(self) -> None:
        # JSON has no tuples, so a round trip returns lists. Coerced here so a
        # reloaded run compares equal to the one that was written -- otherwise the
        # comparability check reports a grid change that never happened.
        self.shape = tuple(self.shape)
        self.voxdims = tuple(self.voxdims)

    @property
    def n_voxels(self) -> int:
        n = 1
        for d in self.shape:
            n *= int(d)
        return n if self.shape else 0

    def describe(self) -> str:
        vox = "x".join(f"{v:g}" for v in self.voxdims) or "?"
        shape = "x".join(str(int(v)) for v in self.shape) or "?"
        head = (
            f"run {self.run_id}  {self.started[:19]}  {self.commit}{'+dirty' if self.dirty else ''}"
        )
        return (
            f"{head}\n"
            f"    {self.recipe} ({self.contrast}), optimize={self.optimize}, search={self.search}\n"
            f"    {len(self.subjects)} subject(s), grid {shape} @ {vox} mm, "
            f"{self.n_mask_voxels} in-mask voxels\n"
            f"    device={self.device}, torch={self.torch_version}"
            + (f"\n    data: {self.note}" if self.note else "")
        )


def capture_run_meta(run_id: int, **kw: Any) -> RunMeta:
    """Build a :class:`RunMeta`, reading the bits that describe the environment."""
    import subprocess

    commit, dirty = "unknown", False
    try:
        root = Path(__file__).resolve().parents[2]
        commit = (
            subprocess.run(
                ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            ).stdout.strip()
            or "unknown"
        )
        dirty = bool(
            subprocess.run(
                ["git", "-C", str(root), "status", "--porcelain"],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            ).stdout.strip()
        )
    except (OSError, subprocess.SubprocessError):  # pragma: no cover - git absent
        pass

    torch_version = ""
    try:
        import torch

        torch_version = torch.__version__
    except ImportError:  # pragma: no cover
        pass

    return RunMeta(
        run_id=run_id,
        started=datetime.datetime.now().isoformat(timespec="seconds"),
        commit=commit,
        dirty=dirty,
        torch_version=torch_version,
        **kw,
    )


def comparability_warnings(runs: list[RunMeta]) -> list[str]:
    """Why an earlier batch of trials may not be comparable with the newest one.

    Warnings, never a refusal. Folding new subjects into an existing study is the
    normal way this tool gets used, and the differences that matter are ones the
    operator can weigh -- so they are stated plainly and the run proceeds.
    """
    if len(runs) < 2:
        return []
    latest, out = runs[-1], []
    for prev in runs[:-1]:
        if prev.commit != latest.commit and "unknown" not in (prev.commit, latest.commit):
            out.append(
                f"run {prev.run_id} was scored at commit {prev.commit}, this one at "
                f"{latest.commit}. If the engines or the metrics changed in between, "
                f"the two sets of scores are not on the same scale."
            )
        if prev.dirty or latest.dirty:
            out.append(
                f"run {prev.run_id if prev.dirty else latest.run_id} was recorded with "
                "uncommitted changes, so its commit does not identify what ran."
            )
        if prev.panel and latest.panel and prev.panel != latest.panel:
            out.append(
                f"run {prev.run_id} was judged by a different panel "
                f"({len(prev.panel)} vs {len(latest.panel)} metrics); consensus ranks "
                "from the two are measuring different things."
            )
        if prev.optimize and prev.optimize != latest.optimize:
            out.append(f"run {prev.run_id} optimised {prev.optimize}, this one {latest.optimize}.")
        if prev.shape and latest.shape and tuple(prev.shape) != tuple(latest.shape):
            out.append(
                f"run {prev.run_id} used a {'x'.join(map(str, prev.shape))} grid, this one "
                f"{'x'.join(map(str, latest.shape))}; per-fit timings are not comparable."
            )
        try:
            delta = datetime.datetime.fromisoformat(
                latest.started
            ) - datetime.datetime.fromisoformat(prev.started)
            if delta.days >= 14:
                out.append(f"run {prev.run_id} is {delta.days} days older than this one.")
        except ValueError:  # pragma: no cover - malformed timestamp
            pass
    return list(dict.fromkeys(out))


@dataclass
class Trial:
    """One backend + config + subject fit, scored and then thrown away."""

    trial_id: int
    config_id: int
    backend: str
    subject: str
    config: dict[str, Any]
    command: list[str]
    seconds: float = 0.0
    scores: dict[str, float] = field(default_factory=dict)
    grade: str = PASS
    reasons: list[str] = field(default_factory=list)
    # Things true of the warp that do not make it wrong -- extreme-but-positive
    # Jacobians. Recorded separately from `reasons` so that a caution can never be
    # mistaken for a rejection by anything reading the table.
    cautions: list[str] = field(default_factory=list)
    warpqc: dict[str, Any] = field(default_factory=dict)
    # Continuous distance from the regularity gate, > 0 == passing. The grade is
    # what a user reads; this is what the adaptive searcher steers by, because a
    # label carries no gradient and this boundary is a cliff.
    margin: float = 0.0
    # Distance to the pass/fail line specifically (folding), as opposed to `margin`
    # above, which also counts the cautions so the searcher can feel them coming.
    # Clearance has to be measured against the line a config can be rejected at.
    gate_margin: float = 0.0
    # Per-level convergence telemetry (formwarp.LevelStats.as_dict()). Answers the
    # question the iteration knobs raise but cannot settle on their own: was this
    # config starved of iterations, or did it over-run and fall back?
    levels: list[dict[str, Any]] = field(default_factory=list)
    run_id: int = 0  # which RunMeta produced this trial
    kept_outputs: str | None = None  # set when a trial was reproduced

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass
class ConfigResult:
    """One config, aggregated over the subjects it was fit on.

    The aggregate is deliberately conservative: the grade is the *worst* grade
    any subject produced, because a setting that folds on one brain out of three
    is not a setting that works. The spread across subjects is reported rather
    than hidden — it is how you tell "we found something" from "we found noise",
    and a parameter in the middle of a wide-but-consistent spread is often the
    right default.
    """

    config_id: int
    backend: str
    config: dict[str, Any]
    n_subjects: int
    score_mean: float
    score_spread: float
    grade: str
    reasons: list[str]
    seconds_mean: float
    # Mean raw value of each panel metric. The consensus score is a rank *within
    # this run*, which is the right unit for picking a winner and useless for
    # comparing one study to another; these are the numbers that transfer.
    abs_scores: dict[str, float] = field(default_factory=dict)
    # Seconds per megavoxel of the base grid, so a timing survives being quoted on
    # a different problem size. Raw seconds do not.
    seconds_per_mvox: float = 0.0
    # Worst subject's distance from the regularity gate, and that distance in units
    # of how much it moves between subjects. The grade says which side of the gate
    # the worst subject landed on; these say whether it landed there by enough to
    # expect the next subject to land there too.
    margin_min: float = 0.0
    margin_z: float | None = None  # None when the run cannot estimate the sigma
    # Distinct caution kinds raised by any subject. Shown, never ranked on.
    cautions: list[str] = field(default_factory=list)
    is_baseline: bool = False

    def label(self) -> str:
        if not self.config:
            return "(defaults)"
        return " ".join(f"{k}={v}" for k, v in sorted(self.config.items()))

    @property
    def narrow(self) -> bool:
        """Passed the gate, but by less than it moves from one subject to the next."""
        return (
            self.grade == PASS
            and not self.is_baseline
            and self.margin_z is not None
            and self.margin_z < NARROW_CLEARANCE_Z
        )

    @property
    def band(self) -> str:
        """What to print in the grade column, and what the ordering keys on."""
        return NARROW if self.narrow else self.grade


# Margins below this are not "close to the gate", they are a warp that came apart:
# at -0.5 the 1st-percentile det(J) is 0.15 against a 0.25 gate. They are dropped
# from the spread estimate as censored, because the failed side is unbounded and a
# handful of blowups otherwise sets the scale for everything -- measured, they take
# the estimate from 0.07 to 0.27, while including or excluding *mild* failures
# moves it by 0.002. The cut is where the answer stops depending on the cut.
NEAR_GATE_FLOOR = -0.5

# Below this many deviations a per-backend estimate is noise, and a backend that
# happened to sit near the gate all run would report a tiny spread and call its
# own squeakers safe. Fall back to the pooled estimate.
MIN_SIGMA_SAMPLES = 8


def margin_subject_sigma(trials: Sequence[Trial]) -> dict[str | None, float]:
    """How much the gate margin moves when a fixed config meets a different brain.

    Pooled *within-config* deviation, so it measures subject-to-subject variation
    and not the between-config variation the search deliberately created. Keyed by
    backend, with ``None`` holding the pooled estimate for backends that have too
    few repeats of their own; an empty dict means the run never fit one config on
    two subjects and so cannot answer.

    Per backend because they genuinely differ -- measured on T1->MNI, qwarp's
    margin moves 0.015 between brains and formwarp's moves 0.10, so one global
    number would call qwarp's real clearance narrow and formwarp's noise safe.

    Truncation is the known bias: a config that failed outright on one subject
    contributes nothing above the floor, and those are the volatile ones. The
    estimate is therefore a floor on the true spread, which is the safe direction
    for a criterion that exists to catch configs that pass by luck.
    """
    by_key: dict[tuple[str, int], list[float]] = {}
    for t in trials:
        if NEAR_GATE_FLOOR < t.gate_margin < MARGIN_LIMIT:
            by_key.setdefault((t.backend, t.config_id), []).append(t.gate_margin)

    devs: dict[str, list[float]] = {}
    for (backend, _cid), vals in by_key.items():
        if len(vals) >= 2:
            mu = statistics.fmean(vals)
            devs.setdefault(backend, []).extend(v - mu for v in vals)

    pooled = [d for v in devs.values() for d in v]
    if len(pooled) < 2:
        return {}

    out: dict[str | None, float] = {}
    sigma_pooled = statistics.pstdev(pooled)
    if sigma_pooled > 0:
        out[None] = sigma_pooled
    for backend, v in devs.items():
        if len(v) >= MIN_SIGMA_SAMPLES:
            sigma = statistics.pstdev(v)
            if sigma > 0:
                out[backend] = sigma
    return out


class TrialStore:
    """Append-only record of every trial, persisted as JSON."""

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.trials: list[Trial] = []
        self.runs: list[RunMeta] = []
        self._next_trial = 0
        self._config_ids: dict[str, int] = {}
        if self.path.exists():
            self.load()

    # --- runs ---------------------------------------------------------------

    def begin_run(self, **kw: Any) -> RunMeta:
        """Open a new batch of trials and record what is producing it.

        Appending rather than replacing: adding subjects to an existing study is
        the normal way this gets used, and the whole point of keeping the earlier
        run's metadata is to be able to say how it differed.
        """
        meta = capture_run_meta(len(self.runs) + 1, **kw)
        self.runs.append(meta)
        return meta

    @property
    def current_run(self) -> int:
        return self.runs[-1].run_id if self.runs else 0

    def warnings(self) -> list[str]:
        """Reasons the runs in this store may not be directly comparable."""
        return comparability_warnings(self.runs)

    # --- identity -----------------------------------------------------------

    def config_id(self, backend: str, config: dict[str, Any]) -> int:
        """Stable id for a (backend, config) pair, so subjects aggregate."""
        key = backend + "|" + json.dumps(config, sort_keys=True, default=str)
        if key not in self._config_ids:
            self._config_ids[key] = len(self._config_ids) + 1
        return self._config_ids[key]

    # --- recording ----------------------------------------------------------

    def add(
        self,
        backend: str,
        subject: str,
        config: dict[str, Any],
        command: list[str],
        **outcome: Any,
    ) -> Trial:
        self._next_trial += 1
        t = Trial(
            trial_id=self._next_trial,
            config_id=self.config_id(backend, config),
            backend=backend,
            subject=subject,
            config=dict(config),
            command=list(command),
            run_id=self.current_run,
            **outcome,
        )
        self.trials.append(t)
        return t

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(
                {
                    "config_ids": self._config_ids,
                    "runs": [asdict(r) for r in self.runs],
                    "trials": [t.as_dict() for t in self.trials],
                },
                indent=2,
                default=str,
            )
        )

    def load(self) -> None:
        raw = json.loads(self.path.read_text())
        self._config_ids = raw.get("config_ids", {})
        # Ignore fields this version does not know about, so a table written by a
        # newer build still opens. A tuning run is expensive; losing one to a
        # schema addition would be the worst possible time to be strict.
        known = {f.name for f in fields(Trial)}
        self.trials = [Trial(**{k: v for k, v in t.items() if k in known}) for t in raw["trials"]]
        run_known = {f.name for f in fields(RunMeta)}
        self.runs = [
            RunMeta(**{k: v for k, v in r.items() if k in run_known}) for r in raw.get("runs", [])
        ]
        self._next_trial = max((t.trial_id for t in self.trials), default=0)
        self._regrade()

    def _regrade(self) -> None:
        """Re-derive every grade from the stored measurements under today's policy.

        What a warp measured is a fact; whether that counts as a failure is a
        policy, and this project has already changed it once (over-compression was
        a hard fail until it was pointed out that a det(J) of 0.2 is unusual
        anatomy rather than impossible anatomy). Keeping the stored verdict would
        leave every table ever written frozen under the rules that happened to be
        in force that afternoon, and silently mixed with tables written under the
        new ones — a comparability trap of exactly the kind ``RunMeta`` exists to
        catch.

        The raw ``WarpQC`` is recorded, so the grade never has to be the thing that
        persists. Trials from before it was recorded keep whatever they were given.
        """
        known = {f.name for f in fields(WarpQC)}
        for t in self.trials:
            if not t.warpqc or not known <= set(t.warpqc):
                continue
            qc = WarpQC(**{k: v for k, v in t.warpqc.items() if k in known})
            t.grade, t.reasons = regularity_verdict(qc)
            t.cautions = regularity_cautions(qc)
            t.margin = regularity_margin(qc)
            t.gate_margin = gate_margin(qc)

    # --- scoring ------------------------------------------------------------

    def compute_consensus(self, panel: Sequence[str]) -> None:
        """Fill in ``scores["consensus"]`` for every trial, using ``panel`` as the jury.

        Consensus is inherently *relative* — each functional votes by ranking the
        candidates it scored — so it cannot be computed when a trial is run, only
        once the field is known. Ranking happens **within a subject**, because a
        functional's absolute value varies more between brains than between the
        settings we are trying to separate; comparing raw values across subjects
        would measure the subjects.

        The panel comes from :func:`allcost.judge_panel` and is not merely "all
        the costs minus the optimised one": it also drops the functionals that
        are *meaningless* for the contrast regime. See that function for why —
        the short version is that on same-modality data three of the fourteen
        rank the worst warp first.
        """
        from .allcost import consensus_rank

        keep = set(panel)
        by_subject: dict[str, list[Trial]] = {}
        for t in self.trials:
            by_subject.setdefault(t.subject, []).append(t)

        for ts in by_subject.values():
            scored = {
                str(t.trial_id): {k: v for k, v in t.scores.items() if k in keep}
                for t in ts
                if t.scores
            }
            scored = {k: v for k, v in scored.items() if v}
            if not scored:
                continue
            ranks = dict(consensus_rank(scored))
            for t in ts:
                if str(t.trial_id) in ranks:
                    t.scores["consensus"] = ranks[str(t.trial_id)]

    # --- aggregation --------------------------------------------------------

    def results(self, score_key: str = "consensus") -> list[ConfigResult]:
        """Aggregate trials into per-config results, best first.

        Ordering puts every passing config above every marginal one and every
        marginal above every failing one, *then* sorts by score. A better
        similarity score never buys its way past a folded warp — that inversion
        is the whole failure mode this tool exists to prevent.

        A pass by a hair is its own band. PASS/FAIL is a threshold on a continuous
        quantity, so a config that cleared it by less than the margin's own
        between-subject spread did not demonstrate a setting that works — it
        demonstrated a draw of subjects that happened to land on the near side.
        Sorting those below the clean passes stops the search's own pressure
        towards less regularization (which always scores better, right up to the
        gate) from being rewarded through configs that barely survive it.
        """
        by_config: dict[int, list[Trial]] = {}
        for t in self.trials:
            by_config.setdefault(t.config_id, []).append(t)

        mvox = (self.runs[-1].n_voxels / 1e6) if self.runs else 0.0
        sigmas = margin_subject_sigma(self.trials)

        out = []
        for cid, ts in by_config.items():
            vals = [t.scores.get(score_key) for t in ts]
            vals = [v for v in vals if v is not None]
            if not vals:
                continue
            worst = max(ts, key=lambda t: GRADE_ORDER.get(t.grade, 3))
            names = {k for t in ts for k in t.scores if k != "consensus"}
            abs_scores = {
                n: statistics.fmean([t.scores[n] for t in ts if n in t.scores])
                for n in sorted(names)
            }
            seconds = statistics.fmean([t.seconds for t in ts])
            # The worst subject, for the same reason the grade is the worst grade.
            margin_min = min(t.gate_margin for t in ts)
            sigma = sigmas.get(ts[0].backend, sigmas.get(None))
            caution_kinds = sorted({c.split(":")[0] for t in ts for c in t.cautions})
            out.append(
                ConfigResult(
                    config_id=cid,
                    backend=ts[0].backend,
                    config=ts[0].config,
                    n_subjects=len(ts),
                    score_mean=statistics.fmean(vals),
                    score_spread=statistics.pstdev(vals) if len(vals) > 1 else 0.0,
                    grade=worst.grade,
                    reasons=worst.reasons,
                    seconds_mean=seconds,
                    abs_scores=abs_scores,
                    seconds_per_mvox=(seconds / mvox) if mvox else 0.0,
                    margin_min=margin_min,
                    cautions=caution_kinds,
                    margin_z=(margin_min / sigma) if sigma else None,
                    is_baseline=ts[0].backend == BASELINE,
                )
            )
        out.sort(key=lambda r: (GRADE_ORDER.get(r.grade, 3), r.narrow, r.score_mean))
        return out

    def baseline(self) -> ConfigResult | None:
        """The do-nothing row, if this run recorded one."""
        return next((r for r in self.results() if r.is_baseline), None)

    # --- reproduction -------------------------------------------------------

    def commands_for(self, config_id: int) -> list[tuple[str, list[str]]]:
        """(subject, command) for every trial of a config — what to re-run."""
        return [(t.subject, t.command) for t in self.trials if t.config_id == config_id]


@dataclass
class KnobEffect:
    """What one parameter does, read off every trial that varied it.

    This is the output the tool exists to produce. Not "the best config for
    subject 3", but "raising this knob helps, on every brain we tried" — which
    is what a default can be built on.
    """

    backend: str
    key: str
    levels: list[tuple[Any, float, float, int]]  # (value, mean score, fold rate, n)
    consistency: float  # fraction of subjects agreeing with the pooled direction
    direction: str  # "lower is better" | "higher is better" | "flat"


def knob_effects(
    store: TrialStore, score_key: str = "consensus", pass_only: bool = True
) -> list[KnobEffect]:
    """Marginal effect of every knob, and how consistent it is across subjects.

    ``pass_only`` averages the score over trials that passed the regularity gate,
    which is not a detail. A folded warp scores *better* — that is what folding
    buys — so a level's mean over all trials is pulled down in proportion to how
    often it broke, and the report ends up recommending the setting that fails
    most. Fold rate is still counted over every trial, so the two columns answer
    the two different questions: "how good when it works" and "how often does it
    work". A level with no passing trials shows ``n/a``, which is the honest
    answer rather than a number that flatters it.

    Deliberately *not* a held-out-subject cross-validation. Nothing is being
    fitted to the subjects — a handful of discrete settings are being compared —
    so there is nothing to overfit and no reason to hold anything back. The
    generalization question here is simply whether a knob pushes the result the
    same way on every brain, and the honest way to answer that is to run them all
    and look at whether the direction agrees. Consistency is the statistic;
    holding out would only cost data.
    """
    by_knob: dict[tuple[str, str], list[Trial]] = {}
    for t in store.trials:
        for key in t.config:
            by_knob.setdefault((t.backend, key), []).append(t)

    out = []
    for (backend, key), ts in sorted(by_knob.items()):
        values = sorted({_hashable(t.config[key]) for t in ts}, key=_sort_key)
        if len(values) < 2:
            continue  # pinned, so it has no measurable effect here

        levels = []
        for v in values:
            sel = [t for t in ts if _hashable(t.config[key]) == v]
            usable = [t for t in sel if t.grade == PASS] if pass_only else sel
            scored = [t.scores[score_key] for t in usable if score_key in t.scores]
            folds = [t for t in sel if t.grade != PASS]
            levels.append(
                (
                    v,
                    statistics.fmean(scored) if scored else float("nan"),
                    len(folds) / len(sel) if sel else 0.0,
                    len(sel),
                )
            )

        # Pooled direction: does the best level sit low or high in the range?
        #
        # A level with no passing trial has no score, and dropping the whole knob
        # for that would hide precisely the most useful knob in the report: the
        # one with a fold cliff in it. So an unscoreable level still appears, with
        # its fold rate, and the direction is read off whatever did pass.
        finite = [(v, s) for v, s, _, _ in levels if s == s]
        if not finite:
            out.append(KnobEffect(backend, key, levels, 0.0, "never passes the gate"))
            continue
        best_v = min(finite, key=lambda p: p[1])[0]
        if len(finite) == 1:
            out.append(KnobEffect(backend, key, levels, 1.0, f"only {best_v} passes the gate"))
            continue
        lo, hi = finite[0][0], finite[-1][0]
        if best_v == lo:
            direction = "lower is better"
        elif best_v == hi:
            direction = "higher is better"
        else:
            direction = f"best near {best_v}"

        # Consistency: how many subjects put their own *marginal* best at the
        # same level. It must be marginal on both sides — comparing the pooled
        # marginal against each subject's best joint config compares two
        # different things and reports nonsense (a knob can look "higher is
        # better, 0% agree", which is incoherent), because the winning joint
        # config's level need not be the level that wins on average.
        per_subject: dict[str, dict[Any, list[float]]] = {}
        for t in ts:
            if pass_only and t.grade != PASS:
                continue
            if score_key in t.scores:
                lvl = _hashable(t.config[key])
                per_subject.setdefault(t.subject, {}).setdefault(lvl, []).append(
                    t.scores[score_key]
                )
        agree = 0
        for levels_for_subject in per_subject.values():
            marginals = {v: statistics.fmean(s) for v, s in levels_for_subject.items() if s}
            if marginals and min(marginals, key=lambda v: marginals[v]) == best_v:
                agree += 1
        consistency = agree / len(per_subject) if per_subject else 0.0

        out.append(KnobEffect(backend, key, levels, consistency, direction))
    return out


def _hashable(v: Any) -> Any:
    return tuple(v) if isinstance(v, list) else v


def _sort_key(v: Any) -> tuple:
    return (0, v, "") if isinstance(v, (int, float)) else (1, 0, str(v))


def format_knob_effects(effects: list[KnobEffect]) -> str:
    """Per-knob table: what each level scored, how often it folded, is it consistent."""
    if not effects:
        return "  (nothing varied yet)"
    lines = [
        "  score = mean over trials that PASSED the gate; not-PASS counts every trial.",
        "  'n/a' means no setting at that level ever produced a sound warp.",
        "",
    ]
    for e in effects:
        lines.append(
            f"  {e.backend}.{e.key}  -- {e.direction}, {e.consistency:.0%} of subjects agree"
        )
        lines.append(f"      {'value':>12s} {'score':>8s} {'not-PASS':>9s} {'n':>4s}")
        for v, score, fold, n in e.levels:
            s = f"{score:8.3f}" if score == score else "     n/a"
            lines.append(f"      {str(v):>12s} {s} {fold:8.0%} {n:4d}")
        lines.append("")
    return "\n".join(lines)


@dataclass
class IterationAdvice:
    """What the iteration ceiling for one backend level should be.

    Derived, not searched. The ceiling is not a quality knob with an interior
    optimum — too few is always wrong and too many is free — so laddering over it
    spends fits to answer a question whose direction is known in advance. What is
    genuinely unknown is *how many* a level actually uses, and that is a
    measurement: run with the ceiling set high and look at where the levels stopped.
    """

    backend: str
    level: int
    n: int
    p50_used: float
    p95_used: int
    max_used: int
    starved_frac: float
    ceiling: int  # what was allowed
    recommended: int

    # The knob to reach for when a level burns iterations rather than converging.
    # qwarp is absent on purpose: it optimises shrinking patches rather than taking
    # steps, so "step size" has no single analogue there.
    STEP_KNOB = {"formwarp": "-grad_step", "optiwarp": "-max_step"}

    @property
    def step_knob(self) -> str | None:
        family = "optiwarp" if self.backend.startswith("optiwarp") else self.backend
        return self.STEP_KNOB.get(family)

    @property
    def crawling(self) -> bool:
        """Using most of a deliberately generous ceiling.

        Early stopping not firing is not a failure of the stopping rule — it means
        the iterations were genuinely being used. But a level that needs hundreds of
        iterations to flatten is usually taking steps that are too small, so the
        useful response is a bigger step, not only a bigger ceiling.
        """
        return self.max_used > self.ceiling // 2

    @property
    def verdict(self) -> str:
        hint = f"; try a larger {self.step_knob}" if self.step_knob else ""
        if self.starved_frac > 0:
            return f"TOO LOW — {self.starved_frac:.0%} of fits cut off while improving{hint}"
        if self.crawling:
            return f"converging slowly ({self.max_used}/{self.ceiling}){hint}"
        if self.recommended < self.ceiling // 2:
            return "generous (fine — headroom is free)"
        return "about right"


def _has_iteration_telemetry(stats: dict) -> bool:
    """Whether a per-level record came from an iterative solver.

    qwarp writes per-patch records into the same field: it optimises shrinking
    patches rather than taking steps, so it has no iteration count, no best
    iterate, and nothing to recommend a ceiling for.
    """
    return "iters_run" in stats


def recommend_iterations(store: TrialStore, headroom: float = 2.0) -> list[IterationAdvice]:
    """Read the iteration ceiling back out of what the levels actually used.

    The recommendation is the worst observed *natural* stopping point with headroom,
    not the average: the ceiling has to accommodate the hardest subject, and the cost
    of it being too high is nothing while the cost of it being too low is a level
    silently truncated mid-improvement. Any level that was ever starved reports its
    own ceiling as a lower bound instead, because a truncated run cannot tell you how
    many iterations it would have used.
    """
    rows: dict[tuple[str, int], list[dict]] = {}
    for t in store.trials:
        for lev, stats in enumerate(t.levels):
            if _has_iteration_telemetry(stats):
                rows.setdefault((t.backend, lev), []).append(stats)

    out = []
    for (backend, lev), stats in sorted(rows.items()):
        used = sorted(s["iters_run"] for s in stats)
        caps = [s["n_iter_cap"] for s in stats]
        starved = sum(bool(s["starved"]) for s in stats) / len(stats)
        p95 = used[min(len(used) - 1, int(0.95 * (len(used) - 1)))]
        out.append(
            IterationAdvice(
                backend=backend,
                level=lev + 1,
                n=len(stats),
                p50_used=statistics.median(used),
                p95_used=p95,
                max_used=used[-1],
                starved_frac=starved,
                ceiling=max(caps),
                recommended=int(round(used[-1] * headroom)),
            )
        )
    return out


def format_iteration_advice(advice: list[IterationAdvice]) -> str:
    """The ceiling report: what each level used, and what to set it to."""
    if not advice:
        return "  (no iteration telemetry recorded)"
    lines = [
        "  Iteration ceilings, measured rather than searched. 'used' is where the level",
        "  actually stopped; the ceiling only has to be comfortably above the worst case.",
        "",
        f"  {'backend':16s} {'lvl':>3s} {'p50':>6s} {'p95':>6s} {'max':>6s} "
        f"{'cap':>6s} {'suggest':>8s}  verdict",
        "  " + "-" * 96,
    ]
    for a in advice:
        lines.append(
            f"  {a.backend:16s} {a.level:>3d} {a.p50_used:6.0f} {a.p95_used:6d} "
            f"{a.max_used:6d} {a.ceiling:6d} {a.recommended:8d}  {a.verdict}"
        )
    if any(a.starved_frac > 0 for a in advice):
        lines += [
            "",
            "  A starved level was still improving when its cap stopped it, so its 'used'",
            "  is a floor, not a measurement. Raise -iters and re-run to see the real number.",
        ]
    if any(a.crawling or a.starved_frac > 0 for a in advice):
        lines += [
            "",
            "  Where early stopping never fired, the iterations were genuinely needed — the",
            "  stopping rule is working. But needing most of a generous ceiling means the",
            "  solver is crawling, so raise the step size before raising the ceiling again.",
        ]
    return "\n".join(lines)


def format_level_gains(store: TrialStore) -> str:
    """What each pyramid level bought, and what it cost, from the runs already done.

    The finest patch size is not a parameter to compare in series -- it is where a
    single trajectory stops. A run at minpatch 5 passes through 25, 19, 13 and 9 on
    its way down, so the cost and benefit of every coarser stopping point is already
    contained in it. Testing each separately pays for the same coarse levels five
    times over, and on a 193^3 pair that is 15-27 s/fit at 25 against 137-240 s at
    the bottom.

    Read the last column: once a level stops buying cost, that is where to stop.
    """
    rows: dict[tuple[str, int], list[dict]] = {}
    for t in store.trials:
        for lv in t.levels:
            if "patch" in lv and "cost_before" in lv:
                rows.setdefault((t.backend, int(lv["patch"])), []).append(lv)
    if not rows:
        return "  (no per-level trajectory recorded -- only qwarp reports one)"

    lines = [
        "  What each pyramid level bought. The levels are one trajectory, not separate",
        "  settings: a fine run passes through every coarser patch size on the way, so",
        "  this answers 'how fine is worth it' without running each size separately.",
        "",
        f"  {'backend':10s} {'patch':>6s} {'sec':>8s} {'cost gain':>10s} {'gain/sec':>9s} "
        f"{'patches':>8s} {'n':>4s}",
        "  " + "-" * 66,
    ]
    for (backend, patch), lv in sorted(rows.items(), key=lambda kv: (kv[0][0], -kv[0][1])):
        sec = statistics.fmean([x["seconds"] for x in lv])
        gain = statistics.fmean([x["cost_before"] - x["cost_after"] for x in lv])
        done = statistics.fmean([x.get("patches_done", 0) for x in lv])
        lines.append(
            f"  {backend:10s} {patch:6d} {sec:8.1f} {gain:10.5f} "
            f"{(gain / sec if sec else 0):9.5f} {done:8.0f} {len(lv):4d}"
        )
    lines += [
        "",
        "  A level with a near-zero gain is one the trajectory could have stopped above.",
    ]
    return "\n".join(lines)


def format_export(store: TrialStore, recipe: str, subjects: str = "") -> str:
    """The run's conclusion as ``Preset`` source, ready to paste into tunespec.

    Deliberately printed for a human to commit rather than written to a file the
    tools read at runtime. A default changing is a real change: it should arrive as
    a reviewable diff with a provenance line attached, not appear because someone
    left a tuning directory lying around. The generated provenance is a starting
    point — the part only the operator knows is what the data actually was.
    """
    best: dict[str, ConfigResult] = {}
    for r in store.results():
        if r.grade == PASS and r.backend not in best:
            best[r.backend] = r
    if not best:
        return "  (no passing config to export — nothing here is fit to be a default)"

    n_subjects = len({t.subject for t in store.trials})
    n_fits = len(store.trials)
    lines = [
        "  Paste into PRESETS in fastfuncstuff/processing/tunespec.py.",
        "  Edit the provenance to say what the data actually was.",
        "",
    ]
    for backend, r in sorted(best.items()):
        cfg = ", ".join(f'"{k}": {v!r}' for k, v in sorted(r.config.items()))
        lines += [
            f'    ("{recipe}", "{backend}"): Preset(',
            f'        recipe="{recipe}",',
            f'        backend="{backend}",',
            f"        config={{{cfg}}},",
            "        provenance=(",
            f'            "{subjects or f"{n_subjects} subjects"}, {n_fits} fits, '
            f'{r.seconds_mean:.1f} s/fit, "',
            f'            "{datetime.date.today().isoformat()}."',
            "        ),",
            "    ),",
        ]
    lines += [
        "",
        "  Sanity-check before committing: a preset is a claim that these settings",
        "  generalize to data of this kind, which one run on one cohort cannot",
        "  establish on its own.",
    ]
    return "\n".join(lines)


def format_convergence(store: TrialStore) -> str:
    """Per backend and level: was it starved of iterations, or did it over-run?

    The iteration knobs cannot answer this from the score alone. A config at the top
    of the iters ladder might be there because more iterations genuinely help, or
    because the ladder is too short to show where it stops helping — and those call
    for opposite actions. ``best_iter`` separates them: a level that was still
    improving when the cap stopped it is starved, and one that peaked early and then
    ran on has iterations to give back.
    """
    rows: dict[tuple[str, int], list[dict]] = {}
    for t in store.trials:
        for lev, stats in enumerate(t.levels):
            if _has_iteration_telemetry(stats):
                rows.setdefault((t.backend, lev), []).append(stats)
    if not rows:
        return "  (no convergence telemetry recorded)"

    lines = [
        "  Per-level iteration behaviour. 'starved' = still improving at the cap, so",
        "  the ladder is too short; 'wasted' = iterations run after the kept one.",
        "",
        f"  {'backend':16s} {'lvl':>3s} {'iters':>6s} {'best@':>6s} {'wasted':>7s} "
        f"{'starved':>8s} {'damped':>7s} {'nolegal':>8s}  n",
        "  " + "-" * 88,
    ]
    for (backend, lev), stats in sorted(rows.items()):
        n = len(stats)
        lines.append(
            f"  {backend:16s} {lev + 1:>3d} "
            f"{statistics.fmean([s['iters_run'] for s in stats]):6.1f} "
            f"{statistics.fmean([s['best_iter'] for s in stats]):6.1f} "
            f"{statistics.fmean([s['wasted_iters'] for s in stats]):7.1f} "
            f"{sum(bool(s['starved']) for s in stats) / n:7.0%} "
            f"{sum(bool(s['damped_iters']) for s in stats) / n:6.0%} "
            f"{sum(bool(s.get('fold_fallback')) for s in stats) / n:7.0%}  {n}"
        )
    return "\n".join(lines)


def headline_metric(results: list[ConfigResult]) -> str | None:
    """Which absolute metric to show beside the rank.

    Preference order is deliberate: ``lncc`` first because it carries local
    structure and is the one metric here that a reader outside this project will
    recognise from ANTs, then ``ls`` as the plain correlation, then whatever exists.
    """
    have = {k for r in results for k in r.abs_scores}
    for preferred in ("lncc", "ls", "mi"):
        if preferred in have:
            return preferred
    return sorted(have)[0] if have else None


@dataclass
class KnobImportance:
    """How much a knob moves the answer, relative to everything else that varied.

    Deliberately a marginal effect size and **not** an ANOVA decomposition. The
    adaptive search does not produce a balanced factorial -- it deliberately spends
    its fits where the surrogate points -- and a variance decomposition on
    unbalanced data attributes the imbalance to whichever factor happens to
    correlate with it. The range of level means is crude, but it degrades honestly.
    """

    backend: str
    key: str
    spread: float  # max - min of the per-level mean score
    share: float  # that spread relative to the whole config range
    n_levels: int
    n_trials: int


def knob_importance(store: TrialStore, score_key: str = "consensus") -> list[KnobImportance]:
    """Rank knobs by how much they actually moved the score. Biggest first.

    This is what says which knobs to keep searching and which to pin. Without it
    the per-knob report shows a direction for every knob equally, whether it is
    worth 70% of the outcome or 2%.
    """
    passing = [t for t in store.trials if t.grade == PASS and score_key in t.scores]
    if not passing:
        return []
    allv = [t.scores[score_key] for t in passing]
    total = (max(allv) - min(allv)) or 1.0

    by_knob: dict[tuple[str, str], list[Trial]] = {}
    for t in passing:
        for key in t.config:
            by_knob.setdefault((t.backend, key), []).append(t)

    out = []
    for (backend, key), ts in by_knob.items():
        levels: dict[Any, list[float]] = {}
        for t in ts:
            levels.setdefault(_hashable(t.config[key]), []).append(t.scores[score_key])
        if len(levels) < 2:
            continue
        means = [statistics.fmean(v) for v in levels.values()]
        spread = max(means) - min(means)
        out.append(KnobImportance(backend, key, spread, spread / total, len(levels), len(ts)))
    out.sort(key=lambda k: -k.share)
    return out


def format_importance(items: list[KnobImportance]) -> str:
    """Which knobs earn their place in the search."""
    if not items:
        return "  (nothing varied enough to rank)"
    lines = [
        "  How much each knob moved the score, as a share of the whole spread across",
        "  configs. A marginal effect size, not an ANOVA -- the adaptive search does not",
        "  produce a balanced design, and a decomposition would launder that imbalance.",
        "",
        f"  {'backend':16s} {'knob':18s} {'share':>7s} {'spread':>8s} {'levels':>7s} {'n':>5s}",
        "  " + "-" * 70,
    ]
    for k in items:
        lines.append(
            f"  {k.backend:16s} {k.key:18s} {k.share:6.0%} {k.spread:8.2f} "
            f"{k.n_levels:7d} {k.n_trials:5d}"
        )
    small = [k for k in items if k.share < 0.05]
    if small:
        lines += [
            "",
            "  Worth pinning with -fix (each moved under 5% of the range): "
            + ", ".join(f"{k.backend}.{k.key}" for k in small[:6]),
        ]
    return "\n".join(lines)


def format_runs(store: TrialStore) -> str:
    """What produced the trials in this store, and how the batches differ."""
    if not store.runs:
        return "  (no run metadata -- this table predates run tracking)"
    lines = [r.describe() for r in store.runs]
    warn = store.warnings()
    if warn:
        lines.append("")
        lines.append("  COMPARABILITY WARNINGS (not blocking):")
        lines += [f"    - {w}" for w in warn]
    return "\n".join("  " + ln if not ln.startswith("  ") else ln for ln in lines)


def format_guide(store: TrialStore, recipe: str) -> str:
    """The alignment recommendation this run supports, as a document.

    Everything here is derived rather than asserted, so a claim cannot outlive the
    evidence for it: the settings come from the winning configs, the "worth it"
    line from the baseline, the timings from the measured fits, and the caveats
    from the run metadata and the comparability warnings.
    """
    results = store.results()
    if not results:
        return "No results yet."
    base = store.baseline()
    metric = headline_metric(results)
    meta = store.runs[-1] if store.runs else None

    out = [f"# Alignment recommendation: {recipe}", ""]
    if meta:
        vox = "x".join(f"{v:g}" for v in meta.voxdims) or "?"
        shape = "x".join(str(int(v)) for v in meta.shape) or "?"
        out += [
            f"Measured on {len(meta.subjects)} subject(s), {shape} @ {vox} mm, "
            f"optimising {meta.optimize}, judged by {len(meta.panel)} metric(s).",
            f"Code {meta.commit}{'+dirty' if meta.dirty else ''}, {meta.started[:10]}, "
            f"device {meta.device}.",
            "",
        ]
        if meta.note:
            out += [f"Data: {meta.note}", ""]

    out += ["## Is nonlinear worth it here?", ""]
    if base is not None and metric:
        best = next((r for r in results if not r.is_baseline), None)
        if best is not None:
            b, g = base.abs_scores.get(metric), best.abs_scores.get(metric)
            if b is not None and g is not None:
                out += [
                    f"Unwarped input scores {metric}={b:.4f}; the best setting reaches "
                    f"{g:.4f}, a change of {g - b:+.4f}.",
                    "",
                ]
    else:
        out += [
            "No baseline was recorded, so this run cannot say whether the nonlinear "
            "step improved on its input at all.",
            "",
        ]

    out += ["## Recommended settings", ""]
    seen: set[str] = set()
    for r in results:
        # A screened-but-unconfirmed config is one brain's opinion. It belongs in
        # the table, where its n is visible, and not in a recommendation — the
        # search deliberately screens on a single subject, so the top of the
        # ranking is full of settings nobody has reproduced yet. This is the brake
        # that used to be supplied by the regularity gate failing the extreme
        # configs; now that an extreme Jacobian is only a caution, it is the only
        # one, and "two brains agreed" is a better reason to trust a setting than
        # "one brain did not fold".
        if r.is_baseline or r.grade != PASS or r.backend in seen or r.n_subjects < 2:
            continue
        seen.add(r.backend)
        note = f" — CAUTION: {', '.join(r.cautions)}" if r.cautions else ""
        out.append(
            f"- **{r.backend}**: `{r.label()}` — {r.seconds_mean:.1f}s/fit"
            + (f" ({r.seconds_per_mvox:.1f}s per megavoxel)" if r.seconds_per_mvox else "")
            + note
        )
    out.append("")
    if any(r.cautions for r in results if r.backend in seen and not r.is_baseline):
        out += [
            "A caution means the deformation is extreme somewhere — heavily compressed "
            "or expanded — without ever inverting. It is reported and not ranked on, "
            "because heads and ventricles vary enough that the bound is a notice "
            "rather than a verdict. Look at the warp before shipping one.",
            "",
        ]

    imp = knob_importance(store)
    if imp:
        out += ["## Which knobs mattered", ""]
        out += [f"- `{k.backend}.{k.key}` — {k.share:.0%} of the spread" for k in imp[:6]]
        out.append("")

    advice = recommend_iterations(store)
    starved = [a for a in advice if a.starved_frac > 0]
    if starved:
        out += [
            "## Iteration ceilings",
            "",
            "Levels that were cut off while still improving, so their settings are a "
            "floor rather than a measurement:",
            "",
        ]
        out += [f"- {a.backend} level {a.level}: used {a.max_used} of {a.ceiling}" for a in starved]
        out.append("")

    out += ["## Caveats", ""]
    if meta:
        out.append(
            f"- Measured on {len(meta.subjects)} subject(s). A preset is a claim about "
            "data *of a kind*, which one cohort cannot establish."
        )
    for w in store.warnings():
        out.append(f"- {w}")
    out.append("- Eyeballs remain the final judge; `-reproduce N` rebuilds any row.")
    return "\n".join(out)


def format_results_table(results: list[ConfigResult], limit: int = 25) -> str:
    """The table the user reads, and picks a number out of to reproduce."""
    if not results:
        return "  (no results yet)"
    metric = headline_metric(results)
    base = next((r for r in results if r.is_baseline), None)
    b_val = base.abs_scores.get(metric) if (base and metric) else None

    head = (
        f"  {'#':>3s}  {'backend':16s} {'score':>8s} {'+/-':>7s} {'grade':9s} "
        f"{'clear':>6s} {'s/fit':>6s}"
    )
    if metric:
        head += f" {metric:>9s}"
        if b_val is not None:
            head += f" {'vs base':>9s}"
    lines = [head + "  settings", "  " + "-" * (len(head) + 30)]
    for r in results[:limit]:
        clear = f"{r.margin_z:6.2f}" if r.margin_z is not None else f"{'-':>6s}"
        # A caution rides in the grade column rather than a column of its own: it
        # is a footnote on the verdict, and giving it a column would imply it ranks.
        band = r.band.upper() + ("*" if r.cautions else "")
        row = (
            f"  {r.config_id:>3d}  {r.backend:16s} {r.score_mean:8.4f} "
            f"{r.score_spread:7.4f} {band:9s} {clear} {r.seconds_mean:6.1f}"
        )
        if metric:
            v = r.abs_scores.get(metric)
            row += f" {v:9.4f}" if v is not None else f" {'-':>9s}"
            if b_val is not None:
                row += f" {v - b_val:+9.4f}" if v is not None else f" {'-':>9s}"
        lines.append(row + f"  {r.label()}")
    if len(results) > limit:
        lines.append(f"  ... {len(results) - limit} more")
    lines.append("")
    if metric:
        lines.append(
            f"  'score' is a rank within this run (lower better); '{metric}' is the raw "
            "value,\n  which is the column that means anything outside it."
        )
    shown = results[:limit]
    if any(r.cautions for r in shown):
        kinds = sorted({c for r in shown for c in r.cautions})
        lines.append(
            f"  '*' carries a caution ({', '.join(kinds)}): the deformation is extreme\n"
            "  somewhere but never inverts. Reported, never ranked on -- heads and\n"
            "  ventricles vary enough that the bound is a notice, not a verdict."
        )
    if any(r.narrow for r in shown):
        lines.append(
            "  'clear' is how far the worst subject sat from the regularity gate, in\n"
            "  units of how far that distance moves between subjects. NARROW means under\n"
            "  1 -- it passed, but not by enough to expect the next brain to pass too."
        )
    if b_val is None:
        lines.append(
            "  No baseline row: this run cannot say whether any setting beat doing nothing."
        )
    lines.append("  Reproduce one with:  ffs_tunewarp ... -reproduce N   (keeps the outputs)")
    return "\n".join(lines)


def format_reproduce(store: TrialStore, config_id: int, out_dir: str | Path) -> str:
    """What re-running a config would do — the commands, verbatim."""
    cmds = store.commands_for(config_id)
    if not cmds:
        return f"No trial with config id {config_id}."
    out = Path(out_dir)
    lines = [f"Config {config_id}: {len(cmds)} fit(s), outputs kept in {out}/"]
    for subject, cmd in cmds:
        lines.append(f"  # {subject}")
        lines.append("  " + " ".join(cmd))
    return "\n".join(lines)
